### ISSUE TITLE
Allow user to select date in the past

### ISSUE THREAD

**Issue by shyam-aloha** [fetrarij/ngx-daterangepicker-material#100]
If user has to select some date from the year 2000, then he needs keep clicking the previous button to get there. Can we have something like material date picker where we can click the year and then we can easily select the year that user wanted.

**Comment by fetrarij** [comment]
Hello @shyam-aloha ,You could use `[showDropdowns]="true"` then you will have a year dropdown.

**Comment by shyam-aloha** [comment]
@fetrarij  - thank you.
