### ISSUE TITLE
The latest minor version contains a breaking change

### ISSUE THREAD

**Issue by cherurg** [fetrarij/ngx-daterangepicker-material#101]
According to [semantic versioning](https://semver.org/) there must not be any breaking changes in minor versions. Any breaking change means upgrade of the major version.

I used `^1.2.7` and several weeks later I got `1.3.x` that contains a [breaking change](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/CHANGELOG.md#130-2019-01-15). Of course, it broke the code.

This may be fixed in two steps:

1) Release of `2.0.x`.
2) Release of `1.3.4` that rollbacks the breaking change and probably contains a noticeable warning of depreciation. It may be an NPM postinstall script (like [here](https://stackoverflow.com/questions/46942043/npm-install-add-custom-warning-message), for example).

P.S. thank you for your work.

**Comment by fetrarij** [comment]
Hello @cherurg  . Thanks for your  report. I didn't think about it since the only change was the forRoot. you are right I need to fix the version

**Comment by fetrarij** [comment]
I've published a new version which is 2.0.0, then 2.0.1 for quick fix.
I've published 1.3.4 also to have the previous functionality.
I've deprecated all version from 1.3.0 since they have a broken update.

Thanks

**Comment by cherurg** [comment]
Thank you!
