### ISSUE TITLE
is it possible to select month and year as drop down values 

### ISSUE THREAD

**Issue by virendra-180kumar** [fetrarij/ngx-daterangepicker-material#103]

**Comment by fetrarij** [comment]
Hello, Use [showDropdowns]="true"

**Comment by Surajit229** [comment]
Anyone can try that:

<input type="text"
  ngxDaterangepickerMd
  [singleDatePicker]="true"
  [autoApply]="true"
  [showDropdowns]="true"
  [locale]="{format: 'DD-MMM-YYYY'}"/>
