### ISSUE TITLE
Timepicker not updated when range clicked

### ISSUE THREAD

**Issue by Michael-Molloy** [fetrarij/ngx-daterangepicker-material#105]
Hello everyone,

When I click on a range, the timepicker doesnt change.

![image](https://user-images.githubusercontent.com/47331238/52226790-e5066200-287b-11e9-8411-9886099837ff.png)

When I select a range, the date is updated, but not the time. In this example, I expected to have 00:00:00 - 23:59:59 which corresponds to my ranges.

Do we have a way to set manually the timepicker? Or can you fix this?

Thanks

**Comment by Michael-Molloy** [comment]
I found something. The method clickRange not call the method renderTimePicker.

![image](https://user-images.githubusercontent.com/47331238/52227483-a8d40100-287d-11e9-8e33-1fe2e37cf368.png)

What do you think?

**Comment by fetrarij** [comment]
Hello. Thanks for the report. I will fix this as soon as possible.

**Comment by fetrarij** [comment]
@Michael-Molloy it's fixed with 2.0.2, however you need to define in your range's array the time you want for start/end for today, yesterday,...

**Comment by Michael-Molloy** [comment]
Thanks @fetrarij
