### ISSUE TITLE
Close dialog after select a predefined range item

### ISSUE THREAD

**Issue by baole** [fetrarij/ngx-daterangepicker-material#106]
How can I make the picker closes after a user selects a predefined range item, such as "Today" or "Yesterday"? Or how can I close the dialog programmatically (such as after rangeClicked() triggered)?

**Comment by MichielMag** [comment]
Do you have the option "keepCalendarOpeningWithRange" on true? If that's false (which it is per default) the calendar should close after choosing a range if I recall correctly.

**Comment by fetrarij** [comment]
hello @baole , sorry for the late reponse.

You can accomplish it by using rangeClicked() then by calling the datepicker directive method `hide()` using viewChild [like this](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.ts)

```
 @ViewChild(DaterangepickerDirective) pickerDirective: DaterangepickerDirective;
  ...
  rangeClicked(range) {
    console.log('[rangeClicked] range is : ', range);
    this.pickerDirective.hide();
  }
```

**Comment by fahadsubzwari924** [comment]
@fetrarij  can you tell me the correct import for `DaterangepickerDirective` ?
