### ISSUE TITLE
Not able to run ng build --prod

### ISSUE THREAD

**Issue by RscAnonymous** [fetrarij/ngx-daterangepicker-material#107]
I am facing the error - Property 'forRoot' does not exist on type 'typeof NgxDaterangepickerMd'.

**Comment by Gag92** [comment]
same issue but error is Nan of undefined

**Comment by fetrarij** [comment]
Hello, which version are you using? and your angular version ?

**Comment by Steeze** [comment]
I'm seeing the following error:  Function calls are not supported in decorators but 'weekdaysMin' was called in 'ɵb' 'ɵb' calls 'weekdaysMin' at ngx-daterangepicker-material\ngx-daterangepicker-material.ts(24,17). during a `ng build -prod`  I'm using Angular 6 and version 1.3.0 of ngx-daterangepicker-material

**Comment by RscAnonymous** [comment]
I have fixed this issue by updating to the latest version NgxDaterangepickerMd.
Version in my package.json file - "ngx-daterangepicker-material": "^2.0.2",

**Comment by fetrarij** [comment]
@Steeze @Gag92 @RscAnonymous use the latest version (v2.0.2), then in your module imports change `NgxDaterangepickerMd` to `NgxDaterangepickerMd.forRoot() `

**Comment by Steeze** [comment]
Thanks @fetrarij @RscAnonymous  for the quick response, I'll update my version and test it out. Thanks

**Comment by Gag92** [comment]
after update of 2.02 everything is working fine , thx guys for quick response, i did even make some restyling )))``
<img width="837" alt="screen shot 2019-02-09 at 11 17 22" src="https://user-images.githubusercontent.com/13536259/52517927-769b1880-2c5c-11e9-8403-08f5f6028f27.png">
