### ISSUE TITLE
Not able to bind / update date from controller in Inline daterangepicker

### ISSUE THREAD

**Issue by NileshRamani** [fetrarij/ngx-daterangepicker-material#108]
I am using angular 5.2.3 and ngx-daterangepicker-material 2.0.2.

When I am try to use [(ngModel)]="selected" attribute it gives me below error: 
![image](https://user-images.githubusercontent.com/5783885/52546963-a4619800-2de9-11e9-923b-8bd4078b3a44.png)

Please let me know what can be wrong.

**Comment by fetrarij** [comment]
Hello @NileshRamani , with the inline mode we cannot use ngModel yet, use  (choosedDate)="choosedDate($event)" and updat the model with this event in your component

**Comment by NileshRamani** [comment]
Hi Fetrarij,

Thanks for providing inputs. 

(choosedDate)="choosedDate($event)" - this is about to getting the selected values from the calendar control. 

Basically, I want to set date in inline calendar when component init event / page load time as past 7 days to today date. 

How I can set a value in inline-calendar control ?

**Comment by fetrarij** [comment]
This could be resolved with viewChild

```
@ViewChild(DaterangepickerComponent) pickerInline: DaterangepickerComponent;
...
ngOnInit() {
    this.pickerInline.setStartDate(moment());
    this.pickerInline.setEndDate(moment().add(5,'days'));
}
```

**Comment by vvpanchenko** [comment]
Faced with the same issue today and have resolved it with ViewChild too. 
Also, in my case datepicker uses ranges (presets), so another workaround to make it selected on init:
```
ngOnInit() {
    this.ngxdaterangepicker.setStartDate(moment());

    this.ngxdaterangepicker.chosenRange = 'Some your suctom label';
    this.ngxdaterangepicker.calculateChosenLabel();
    ...
}
```

**Comment by vvpanchenko** [comment]
Faced with the same issue today and have resolved it with ViewChild too. 
Also, in my case datepicker uses ranges (presets), so another workaround to make it selected on init:
```
ngOnInit() {
    this.ngxdaterangepicker.setStartDate(moment());

    this.ngxdaterangepicker.chosenRange = 'Your_Selected_Range_Name';
    this.ngxdaterangepicker.calculateChosenLabel();
    ...
}
```

**Comment by NileshRamani** [comment]
Thanks for providing inputs.

@fetrarij @vvpanchenko your both reply is very helpful for me, thanks again.
