### ISSUE TITLE
how to encapsulate as one component

### ISSUE THREAD

**Issue by finley-fuelx** [fetrarij/ngx-daterangepicker-material#109]
right now many places used in the below duplicate code, I want to encapsulate as independent component for reuse.
```
<div class="fx-date-range-container">
  <span class="summary">Summary</span>
  <input class="fx-date-range" type="text" matInput
         ngxDaterangepickerMd
         [locale]="{applyLabel: 'ok', format: 'MM-DD-YYYY'}"
         [drops]="'down'"
         [opens]="'right'"
         [ranges]="ranges"
         [showCustomRangeLabel]="false"
         [alwaysShowCalendars]="true"
         [keepCalendarOpeningWithRange]="true"
         [showCancel]="true"
         autocomplete="off"
         [(ngModel)]="selectedDateRange"
         (change)="getCampaignFXASummary()"
         name="daterange"/>
  <mat-icon class="icon-date-range" matSuffix>keyboard_arrow_down</mat-icon>
</div>
```
the component name is fx-date-range-picker
here is demo, my question is how to set ngModel and pass the value into  fx-date-range-picker component.
I don't know how to implement writeValue function... 
https://ngx-daterangepicker-material-demo.stackblitz.io

**Comment by fetrarij** [comment]
hello @finley-fuelx , look into [daterangepicker.directive.ts](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/src/daterangepicker/daterangepicker.directive.ts) , imo you can reuse these code
