### ISSUE TITLE
Clear selection

### ISSUE THREAD

**Issue by zolakt** [fetrarij/ngx-daterangepicker-material#11]
This is a feature request.
It would be useful if there was a way to clear selection. I use this to filter records. It would be very useful if I could just clear the filter to get all values, instead of picking a large timespan (and still filtering with the values in the DB or wherever).

Currently, I tried deleting it with backspace, but as soon as the input is focused the calendar opens and overlaps it. A button inside calendar for clearing would be nice. Also an exposed method would be useful, so for example I could add a suffix icon to the input that calls it

**Comment by fetrarij** [comment]
Hello, this feature is now available with v1.1.0, 
Thank you!

**Comment by zolakt** [comment]
Thanks for the updates. Great job!

**Comment by BruceMoose** [comment]
How do I clear input field by my custom button?
I use this to search data from database , while it have a clear button , if button is clicked , the input field is not cleared .

In .html file

`<input type="text" ngxDaterangepickerMd 
    [(ngModel)]="selected" class="form-control"
    [showCustomRangeLabel]="true"
    [alwaysShowCalendars]="true"
    [ranges]="ranges"
    [linkedCalendars]="false"
    [showClearButton]="true"
    [showDropdowns]="true"/> 
`

In .ts file

`selected: any;`
`clear() {
    this.keyword = ""
    this.selected = null
    this.refresh();
  }`
>

**Comment by yousefkhan** [comment]
@BruceMoose Did you find any way to clear the input field?

**Comment by alkasinha201** [comment]
I  also want to use a custom button to reset all the fields on my page including this Date Picker field. My code is similar to what @BruceMoose  has shown above. I can see that clear function has been committed in the directive 11 days back. But I guess it is not yet released because I did not get this change when I took update. 

Is it possible to release this change since i really need it? OR  Is there any planned date for that?
@fetrarij

**Comment by yousefkhan** [comment]
@alkasinha201 You can use https://github.com/yousefkhan/ngx-daterangepicker-material2 if you like. I customized it and added some options including clear option.

**Comment by fetrarij** [comment]
@alkasinha201 @yousefkhan  Hello, I didn't see your message. I will check and do a release.

**Comment by fetrarij** [comment]
@yousefkhan You can create a PR if you want to contribute

**Comment by fetrarij** [comment]
@zolakt @BruceMoose @alkasinha201 with the new version (v1.2.5) you can just set the model to null and it clear the input directly.

**Comment by alkasinha201** [comment]
@fetrarij Thanks for the update! :)

**Comment by sanket-kumawat** [comment]
> @zolakt @BruceMoose @alkasinha201 with the new version (v1.2.5) you can just set the model to null and it clear the input directly.
Hey, can you please tell me how can I do this in reactive form.
