### ISSUE TITLE
Unable to get Custom Range label and calendar can't update on select last month range.

### ISSUE THREAD

**Issue by pratikEbr** [fetrarij/ngx-daterangepicker-material#112]
Hello,
Thank you for this awesome component for angular. I implemented it but facing a problem on below two point. Can you please look in this?

**1. Unable to get Custom Range label.**

 ranges: any = {
    'Today': [moment(), moment()],
    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
    'This Month': [moment().startOf('month'), moment().endOf('month')],
    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
  }

I used the **rangeClicked** like below function but I unable to get Custom Range label. when I select the custom date or click on the custom range Range. All above ranges works fine.

rangeClicked(range) {
  console.log( range.label);
}

2. Calendar can't update on select last month range.
 
When I click on the last month range calendar can't auto update to last month dates. I click the manually on previous button then it shows . 

![screenshot 2019-02-20 at 9 00 07 am](https://user-images.githubusercontent.com/47788436/53064991-d5c81b00-34ef-11e9-83c0-19ac5c90804f.png)

Thank you Again..

**Comment by sash1401** [comment]
Hi fetrarij ,
Any update on the above issue or work-around that u could suggest?

**Comment by fetrarij** [comment]
Hi. I m on holidays, will look on this as soon as possible

**Comment by fetrarij** [comment]
hello @sash1401 ,sorry for the late response. How is your html?
do you use `(rangeClicked)="rangeClicked($event)` ?

**Comment by fetrarij** [comment]
@sash1401 Hi, I need update to let this issue open, dont hesitate to reopen if you still need help. Thanks

**Comment by sriprakachu** [comment]
I face the same issue for custom range selection. I get the dates shown in ui instead of the custom range label. Could you please suggest a solution?

**Comment by dentkachuk** [comment]
Have the same issue, just ranges from the object are returned but I need to know that "Custom range" was clicked. Because I need customize calendars.

**Comment by roxheifraholli1** [comment]
custom range is not working when a date is selected

**Comment by Franccescalee** [comment]
Same issue here. rangeClicked doesn't fire when "Custom range" is clicked.
