### ISSUE TITLE
[locale]="{firstDay: 1}" jumps day label with multiple components

### ISSUE THREAD

**Issue by daanvanrobays** [fetrarij/ngx-daterangepicker-material#114]
Hello,

**ISSUE**
I've noticed the following weird behaviour on the day label when you have a website with more than 1 of this component on various pages.
![image](https://user-images.githubusercontent.com/10880307/53101641-7804f480-352a-11e9-9e6c-80c2fd37196a.png)

when you set [locale]="{firstDay: 1}" inline or as a locale setting and you open multiple datepicker components after each other (not simultaneously) it will jump the day label by 1 (monday -> tuesday, tuesday -> wednesday, etc..)

**REPRODUCE**
1. Go to the [demo page](https://fetrarij.github.io/ngx-daterangepicker-material/single-datepicker) and navigate to 'Single Datepicker' 
2. Open the datepicker and watch the day label
3. Navigate to 'Custom Ranges'
4. Open the datepicker
5. Navigate back to 'Single Datepicker' 
6. Open the datepicker and notice the day label has jumped 1 position

**Comment by veerritu** [comment]
@daanvanrobays  well the same thing was happening with me , but I just added it inside ngOnit() and it worked fine then . You can try this.
@fetrarij  I was able to reproduce this issue as well .

**Comment by daanvanrobays** [comment]
Thanks @veerritu, I'll give it a shot

**Comment by StefanGramadnikov** [comment]
Hi all,

I had the same issue and I was able to work around it by setting the locale in the ngOnInit() function.
Also you I had to specify the days of the week. 

`this.pickerLocale = {firstDay: 1, daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']} ;`

**Comment by fetrarij** [comment]
this commit fix this https://github.com/fetrarij/ngx-daterangepicker-material/commit/d52868ebabbc5783fc0596baa2df11f86f72e043

**Comment by loonix** [comment]
if anyone comes to look at this and needs a function that does it dynamically depending on the passed in week first day:

```ts
  getWeekdays(weekFirstDay: 'su' | 'mo' | 'tu' | 'we' | 'th' | 'fr' | 'sa') {
    const weekFirstDayIndex = this.weekdays.indexOf(weekFirstDay);
    return [
      ...this.weekdays.slice(weekFirstDayIndex).map(day => day.toUpperCase()),
      ...this.weekdays.slice(0, weekFirstDayIndex).map(day => day.toUpperCase())
    ];
  }
  ```
