### ISSUE TITLE
dates are not updated in calendar dynamically if changed from input field

### ISSUE THREAD

**Issue by veerritu** [fetrarij/ngx-daterangepicker-material#115]
Hi ,

Is there any support for dates typed from input field should update the calendar date?

Right now its not updating dynamically.

![image](https://user-images.githubusercontent.com/32728268/53317496-d7c81a80-38f1-11e9-83b8-0535ba6b25c6.png)

**Comment by eRif84** [comment]
Hi,

i have the same question/problem.

**Comment by fetrarij** [comment]
Hi, This is a feature request. Will work on this when have time ;), thanks

**Comment by veerritu** [comment]
Hi @fetrarij ,

Did u get anytime for this?
or if you have any idea how we can proceed with this , input field to be editable with date validation and dynamic update in calendar.

**Comment by fetrarij** [comment]
@veerritu hi, dont have time yet but I really wanna work on it.
But I will accept PR if you wanna work on it too ;)

**Comment by mathurpranjal01** [comment]
Hi @fetrarij , I used ngx daterangepicker (dual calender) .. I am able to fetch current date and time but it fails if I keep my app stable for say one hour and choose "last 12 hours" . it will calculate hours from one hour back, and not the current local time unless I refresh it ! any solution ?
