### ISSUE TITLE
Easily customize the theme

### ISSUE THREAD

**Issue by Kaitis** [fetrarij/ngx-daterangepicker-material#116]
Hello, thanks for sharing this. Quick (maybe stupid) question: How can I override the styles when used as a directive on an input? Specifically panel background and calendar background

**Comment by ipavlyk** [comment]
@Kaitis I had the similar case. I tried to override styles but overrides didn't apply. Then I've just set `encapsulation: ViewEncapsulation.None` into my component and overrides appeared.

**Comment by fetrarij** [comment]
normally you could change theses styles easily. Just put in the main style of your app (eg: app/style.css)
