### ISSUE TITLE
Is there an option dateLimit?

### ISSUE THREAD

**Issue by eRif84** [fetrarij/ngx-daterangepicker-material#118]
Hello,

is there an option dateLimit like the dateLimit Option in the bootstrap daterangepicker?

**Comment by fetrarij** [comment]
Hello,

this should have this but may be not configurable externally with attribute (Input misse)..
Could you explain what it does and I will add it?

Thanks

**Comment by eRif84** [comment]
Hi,

thanks for your fast reply.

If define a date limit (for example 7 days) and i choose
the date 25 April then it should only the next seven days available for choosing.

**Comment by fetrarij** [comment]
Ah okay @eRif84 will activate it
