### ISSUE TITLE
Is there an option to get selected label and the date range ? 

### ISSUE THREAD

**Issue by sash1401** [fetrarij/ngx-daterangepicker-material#119]
Is there an option to get selected label and the date range on the input field after picking the date  ?  Something like this  Today (14-03-2019) or CustomRange( 12-02-2019 To 10-03-2019)

**Comment by fetrarij** [comment]
Hello @sash1401 , yes by using the `rangeClicked` event

> (rangeClicked)
Fired when clicked on range, and send an object with range label and dates value, eg: {label: 'This Month', dates: [Moment, Moment]}
