### ISSUE TITLE
Ability to style/mark dates

### ISSUE THREAD

**Issue by cdelgadob** [fetrarij/ngx-daterangepicker-material#12]
In the original [daterangepicker](https://www.npmjs.com/package/daterangepicker) project there were a couple of functions to style and mark as invalid certain days.

Is that possible with yours?

The functions I'm referring to are:
isInvalidDate: (function) A function that is passed each date in the two calendars before they are displayed, and may return true or false to indicate whether that date should be available for selection or not.
isCustomDate: (function) A function that is passed each date in the two calendars before they are displayed, and may return a string or array of CSS class names to apply to that date's calendar cell.

**Comment by fetrarij** [comment]
You can now use: `isInvalidDate` and `isCustomDate`

example of usage: [html](https://github.com/fetrarij/ngx-daterangepicker-material/blob/145bbf5c3401c00545608e9e8286fa58e45e51c4/demo/src/app/single-datepicker/single-datepicker.component.html) and [typescript](https://github.com/fetrarij/ngx-daterangepicker-material/blob/145bbf5c3401c00545608e9e8286fa58e45e51c4/demo/src/app/single-datepicker/single-datepicker.component.ts)
