### ISSUE TITLE
set date on inline calendar

### ISSUE THREAD

**Issue by Worthy7** [fetrarij/ngx-daterangepicker-material#123]
It seems there isn't a simple example which shows how to set the date of the inline version of the calendar.

**Comment by jcjobin** [comment]
What do you mean by "set date"? Are you asking about loading the calendar with a default range selected? If yes, then I am looking for the same thing and will let you know if I get something. If not, then you can set the date by "datesUpdated" or "rangeClicked" events.

**Comment by jcjobin** [comment]
FYI, I was able to get the calendar to load with selected dates by doing the following:
```
  @ViewChild(DaterangepickerComponent) datePicker: DaterangepickerComponent;

  ngOnInit() {
    this.datePicker.setStartDate(moment().startOf('month'));
    this.datePicker.setEndDate(moment().endOf('month'));
  }
```
This will select "This Month" by default.

**Comment by jcjobin** [comment]
And to pick a range:

```
  ranges: any = {
    'Last Week': [moment().subtract(1, 'week').startOf('week'), moment().subtract(1, 'week').endOf('week')],
    'This Week': [moment().startOf('week'), moment().endOf('week')],
    'Next Week': [moment().add(1, 'week').startOf('week'), moment().add(1, 'week').endOf('week')],
    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
    'This Month': [moment().startOf('month'), moment().endOf('month')],
    'Next Month': [moment().add(1, 'month').startOf('month'), moment().add(1, 'month').endOf('month')],
  };
  this.datePicker.ranges = this.ranges;
  this.datePicker.clickRange('', 'This Month');
```

**Comment by fetrarij** [comment]
> FYI, I was able to get the calendar to load with selected dates by doing the following:
> 
> ```
>   @ViewChild(DaterangepickerComponent) datePicker: DaterangepickerComponent;
> 
>   ngOnInit() {
>     this.datePicker.setStartDate(moment().startOf('month'));
>     this.datePicker.setEndDate(moment().endOf('month'));
>   }
> ```
> This will select "This Month" by default.

This is the solution with inline datetimepicker. Thanks @jcjobin

**Comment by GSAIPAVANKUMAR** [comment]
Solution is not working

**Comment by ravi-pandit-dits14** [comment]
@fetrarij compile time error
`Property 'setEndDate' does not exist on type 'DaterangepickerDirective'`
