### ISSUE TITLE
Hiding the dates in other months displayed at beginning and end of this calendar

### ISSUE THREAD

**Issue by mtabishs** [fetrarij/ngx-daterangepicker-material#126]
Hi,
I want to Hide the dates in other months displayed at beginning and end of this calendar.
Only show current month dates in range calendar.

Regards,

Tabish Siddiqui
Senior Software Engineer

**Comment by fetrarij** [comment]
Hello, using minDate and maxDate doesnt help you accomplishing this?

**Comment by RtzS** [comment]
Hi

I am also trying to hide dates from other month in current month. 
Min and max date is  not helpful to achieve this. 
Tried with "emptyWeekRowClass" as well but it is not working in 2.1.10 version.
Can any one help me to solve this. PFA.

![image](https://user-images.githubusercontent.com/8089250/84994405-445ecc80-b168-11ea-897c-6d6c62fdc402.png)

Thankyou in advance.
Any help to solve this will be appreciated.
