### ISSUE TITLE
Clicking on icon doesn't show calendar

### ISSUE THREAD

**Issue by dsantaolallam** [fetrarij/ngx-daterangepicker-material#127]
Hi, I've got an issue that we could fix before, but after an update it stopped working again.

In the input div, when the calendar icon is clicked, the calendar doesn't show, it is necessary to click on the input textbox for the calendar to open.

We could fix this before by adding the class .ngx-daterangepicker-action but after the update where the timer was added this solution stopped working .

`                                <mat-icon matSuffix><i class="ngx-daterangepicker-action far fa-calendar-alt fa-xs"></i></mat-icon>                        
`

**Comment by sierrodc** [comment]
> Hi, I've got an issue that we could fix before, but after an update it stopped working again.
> 
> In the input div, when the calendar icon is clicked, the calendar doesn't show, it is necessary to click on the input textbox for the calendar to open.
> 
> We could fix this before by adding the class .ngx-daterangepicker-action but after the update where the timer was added this solution stopped working .
> 
> ` <mat-icon matSuffix><i class="ngx-daterangepicker-action far fa-calendar-alt fa-xs"></i></mat-icon> `

Hi,

 this code works for me:

`<mat-icon class="ngx-daterangepicker-action" matSuffix style="cursor: pointer" (click)="openRangeDatePicker($event)">date_range</mat-icon>`

and in component file:

```
public openRangeDatePicker($event) {
      this.pickerDirective.open($event);
}
```

if it's not working, try to add a breakpoint in outsideClick function (last function of daterangepicker.directive.ts).

**Comment by fetrarij** [comment]
Hello @dsantaolallam , could you give more detail? how is your component? 
Take a look on the demo [here the html](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.html) and [here the typescript ](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.ts)

**Comment by dsantaolallam** [comment]
> > Hi, I've got an issue that we could fix before, but after an update it stopped working again.
> > In the input div, when the calendar icon is clicked, the calendar doesn't show, it is necessary to click on the input textbox for the calendar to open.
> > We could fix this before by adding the class .ngx-daterangepicker-action but after the update where the timer was added this solution stopped working .
> > `<mat-icon matSuffix><i class="ngx-daterangepicker-action far fa-calendar-alt fa-xs"></i></mat-icon>`
> 
> Hi,
> 
> this code works for me:
> 
> `<mat-icon class="ngx-daterangepicker-action" matSuffix style="cursor: pointer" (click)="openRangeDatePicker($event)">date_range</mat-icon>`
> 
> and in component file:
> 
> ```
> public openRangeDatePicker($event) {
>       this.pickerDirective.open($event);
> }
> ```
> if it's not working, try to add a breakpoint in outsideClick function (last function of daterangepicker.directive.ts).

That worked! Thank you very much! I didn't declared the click event.
