### ISSUE TITLE
mat-form-field as wrapper

### ISSUE THREAD

**Issue by bear-wolf** [fetrarij/ngx-daterangepicker-material#130]
Hello.
I use angular 5.2 material and I have this like [example](http://joxi.ru/LmGLLB8TwZe412)
I get some error like this
ERROR Error: mat-form-field must contain a MatFormFieldControl.
 

I want 
Regards,

Andrew Baranov
Middle Software Engineer

**Comment by lahiruchandima** [comment]
Try adding `matInput` to your input

<input matInput type="text" ngxDaterangepickerMd [(ngModel)]="selected" class="form-control"/>

**Comment by fetrarij** [comment]
@bear-wolf Hi, add matInput in  your input as @lahiruchandima said above.

Thanks
