### ISSUE TITLE
datepicker in mat-form-field takes his width

### ISSUE THREAD

**Issue by SzymonKrysztofiak** [fetrarij/ngx-daterangepicker-material#134]
If we want to use material design input, we need to put it in the <mat-form-field> tag. So, then there is a problem with the width of a datepicker (datepicker takes parent width).

```
<mat-form-field>
  <input
    matInput
    type="text"
    ngxDaterangepickerMd
    [(ngModel)]="selected"
    [ranges]="ranges"
    [alwaysShowCalendars]="true"
    (datesUpdated)="getPeriod($event)"
    class="form-control input"
  />
</mat-form-field>
```

That looks datepicker on desktop view:

<img width="278" alt="Zrzut ekranu 2019-04-26 o 09 13 02" src="https://user-images.githubusercontent.com/34811859/56790400-c70a2700-6804-11e9-9c99-ce1d578d7f4f.png">

Even in the demo site input is just styled without the material design wrapper.

**Comment by fetrarij** [comment]
Hello @SzymonKrysztofiak , set in your global style (eg: src/style.css):

```
.md-drppicker {
    width: 556px !important;
}
```
