### ISSUE TITLE
customize days and month text, ex: { days: [ 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz']

### ISSUE THREAD

**Issue by abdullahcel1k** [fetrarij/ngx-daterangepicker-material#137]
customize days and month text, ex: { days: [ 'Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'] }

**Comment by fetrarij** [comment]
hello @abdullahcel1k which language are these?

**Comment by fetrarij** [comment]
@abdullahcel1k globally in  your locale config, you can set the  `daysOfWeek`:  
eg:` {daysOfWeek:  ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'] }`

But considering you are using turkey language, it would be very easy to use something like:

```
import * as moment from 'moment';
import * as localization from 'moment/locale/tr';

moment.locale('tr', localization)
@NgModule({
imports: [
  ...,
  NgxDaterangepickerMd.forRoot({
      applyLabel: 'Okay',
      customRangeLabel: 'CustomRangeLable',
      daysOfWeek: moment.weekdaysMin(),
      monthNames: moment.monthsShort(),
      firstDay: moment.localeData().firstDayOfWeek(),
    }),
  ...
```
