### ISSUE TITLE
Focus and Blur Event or Dropdown icon

### ISSUE THREAD

**Issue by piyushmanurkar** [fetrarij/ngx-daterangepicker-material#138]
Hello Team,
Can you please add dropdown icon
or
Focus/Blur events or Open/Close states...

**Comment by fetrarij** [comment]
Hello @piyushmanurkar , could you gime more info because there are already open and close method in the directive and component. For the state, you can use the `picker.isShown`

**Comment by piyushmanurkar** [comment]
Hello @fetrarij 
Thank you,
I wanted this. Please update your docs for methods.
Thanx again... :)

**Comment by piyushmanurkar** [comment]
Thank you

**Comment by abhishek-g** [comment]
Can Someone help me out with docs for blur/focus events

**Comment by fetrarij** [comment]
@abhishek-g what exactly do you want to have?

**Comment by abhishek-g** [comment]
I want to hook on to the opens/close event if any of the daterangepicker. I have some custom logic that needs to be implemented in the same. If any docs present or any help for the same will be much appreciated.
