### ISSUE TITLE
keepCalendarOpeningWithRange  is not working

### ISSUE THREAD

**Issue by playerfong** [fetrarij/ngx-daterangepicker-material#147]
Can I know why the keepCalendarOpeningWithRange is not working when alwaysShowCalendars is false? 

<input type="text"
                       ngxDaterangepickerMd
                       [showCustomRangeLabel]="false"
                       [alwaysShowCalendars]="false"
                       [keepCalendarOpeningWithRange]="true"
                       [ranges]="ranges"
                       [showClearButton]="false"
                       [showCancel]="false"
                       [linkedCalendars]="true"
                       [showRangeLabelOnInput]="true"
                       formControlName="selected"
                       class="form-control"
                       placeholder="Select please..."/>

**Comment by fetrarij** [comment]
hello @playerfong , what behaviour do you want to accomplish there?
you can just set alwaysShowCalendars = false and keepCalendarOpeningWithRange = false ..
