### ISSUE TITLE
Not Properly Working Need Help

### ISSUE THREAD

**Issue by abhisheksharma662** [fetrarij/ngx-daterangepicker-material#149]
<input type="text" ngxDaterangepickerMd [(ngModel)]="abhishek" [autoApply]="true" class="date" placeholder="Start Date - End Date" [locale]="{format: 'DD-MM-YYYY'}" startKey="start_date" endKey="end_date" />
**Above is my input** 

when i console abhishek model it shows the below record .

{start_date: Moment, end_date: Moment}
end_date: Moment {_isAMomentObject: true, _i: Array(6), _isUTC: false, _pf: {…}, _locale: Locale, …}
start_date: Moment {_isAMomentObject: true, _i: Array(6), _isUTC: false, _pf: {…}, _locale: Locale, …}
__proto__: Object

HOW i will get the exect date and time format to sent to api ?

**Comment by fetrarij** [comment]
@abhisheksharma662 which format do you want? just use moment().format() or moment().toJSON()

**Comment by abhisheksharma662** [comment]
selected: {startDate: Moment, endDate: Moment};

here i need to use it like 
selected: {startDate: moment().toJSON(), endDate: moment().toJSON()};

i atchully need the format like 
2019-05-21T12:06:27.618+05:30

**Comment by fetrarij** [comment]
so just  handle this before sending to api. Something like:
```
submit() {
  const selected = { startDate: startDate.toJSON(), endDate: endDate.toJSON()}
  // now sending to api
  api.send(selected);
}
```

**Comment by abhisheksharma662** [comment]
error TS2304: Cannot find name 'Moment'.
TS2304: Cannot find name 'startDate'.

sir can you please come to skype and please see and guide me the correct way to use this ?

**Comment by fetrarij** [comment]
@abhisheksharma662 this is just a typescript code. Sorry bu I dont have time for skype :(

```
const selected = { startDate: this.selected.startDate.toJSON(), endDate: this.selected.endDate.toJSON()}
  // now sending to api
  api.send(selected)
```

**Comment by abhisheksharma662** [comment]
Still the error is same sir let me paste my ts file code here 

import { Component, OnInit, Inject } from '@angular/core';
import { NgxPaginationModule } from 'ngx-pagination';
import { ActivatedRoute, Router, Params } from '@angular/router';
import { RestserviceService } from '../restservice.service';
import { PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';
import Swal from 'sweetalert2';
declare var jQuery: any;
declare var window: any;
declare var Cookies: any;
import { environment } from 'environments/environment';
@Component({
  selector: 'app-lead-list',
  templateUrl: './lead-list.component.html',
  styleUrls: ['./lead-list.component.css']
})
export class LeadListComponent implements OnInit {
selected: {startDate: Moment, endDate: Moment};
submit() {

      const selected = { startDate: this.selected.startDate.toJSON(), endDate: this.selected.endDate.toJSON()}
      console.log(selected)
  }

}

**Comment by abhisheksharma662** [comment]
please sir sort out my problem because this datepicker is perfect for my project and there is no avilable like this .

**Comment by fetrarij** [comment]
does not it solved your issue?

**Comment by abhisheksharma662** [comment]
no sir still error is here 

 error TS2304: Cannot find name 'Moment'.
  error TS2304: Cannot find name 'Moment'.
 error TS2304: Cannot find name 'startDate'.
 error TS2304: Cannot find name 'endDate'.

**Comment by fetrarij** [comment]
check how we use moment here https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.ts

Use 
```
import * as moment from "moment"
...
moment.Moment
```

**Comment by abhisheksharma662** [comment]
Moment Error is gone sir only 
error TS2304: Cannot find name 'startDate'.
error TS2304: Cannot find name 'endDate'.

const selected = { startDate: startDate.toJSON(), endDate: endDate.toJSON()}
in the above code

**Comment by fetrarij** [comment]
Use this.selected.startDate.toJSON() instead of startDate.toJSON()

**Comment by abhisheksharma662** [comment]
Terminal ERROR are gone but browser console is throwing error 
const selected = { startDate: this.selected.startDate.toJSON(), endDate: this.selected.endDate.toJSON()}


in the above line 
ERROR TypeError: Cannot read property 'startDate' of undefined

**Comment by fetrarij** [comment]
Check if input [(ngModel)]="selected" its selected. And you should check if a date is selected before submitting

**Comment by abhisheksharma662** [comment]
working correctly but 

only working when i click to button after selecting date 
cant this work like if i am not selecting date it will return the blank value 

instead of returning blank value its throwing error 
ERROR TypeError: Cannot read property 'startDate' of undefined



because on fetching data i need to pre pass the parameters weather parameter is blank or filled

**Comment by fetrarij** [comment]
Just add a condition

**Comment by abhisheksharma662** [comment]
last help please 

can you please paste the condition because i am trying to paste but error are coming

**Comment by abhisheksharma662** [comment]
if(this.selected.startDate){
      this.selected.startDate.toJSON()
    }
this condition i added but error is comming 

this condition i added

**Comment by fetrarij** [comment]
If (this.selected && this.selected.startDate) {}

Are you new in js/ts development?
