### ISSUE TITLE
Set date through text input

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [fetrarij/ngx-daterangepicker-material#150]
Hello,

Is it possible to set the date  by typing the date value in the input text box as well as selecting using the date picker?

I have a single date picker as follows:

```
                    <input type="text" id="myDate" name="myDate" ngxDaterangepickerMd [(ngModel)]="myDate"
                           class="form-control form-control-sm"  style="margin-bottom: 8px"
                           [singleDatePicker]="true" [autoApply]="true" [locale]="{format: 'DD/MM/YYYY'}"/>
```
I can update the model value of myDate when using the date picker but not when I type the value in.  Is it supported?

**Comment by fetrarij** [comment]
Hello @SachinSharmaEarthport ,

Actually this doesnt supported yet. But for sure I will work on this.
There are already an issue for it https://github.com/fetrarij/ngx-daterangepicker-material/issues/115

So I'm closing this now.

**Comment by hariniiiiii** [comment]
Hello,

Is it possible to set the date by typing the date value in the input text box as well as selecting using the date picker?

I have a single date picker as follows:

                    <input type="text" id="myDate" name="myDate" ngxDaterangepickerMd [(ngModel)]="myDate"
                           class="form-control form-control-sm"  style="margin-bottom: 8px"
                           [singleDatePicker]="true" [autoApply]="true" [locale]="{format: 'DD/MM/YYYY'}"/>
I can update the model value of myDate when using the date picker but not when I type the value in. Is it supported?
