### ISSUE TITLE
Current month on the left after opening the calendar

### ISSUE THREAD

**Issue by batgos** [fetrarij/ngx-daterangepicker-material#154]
Hello,
When i open the calendar for the first time my current month is on the left with next month on the right.
Exemple : 
![image](https://user-images.githubusercontent.com/9460795/58341261-208a6380-7e4e-11e9-9a04-ee7abb426abc.png)

Do there is a way to fix it pls?
Thanks

**Comment by stellaLight** [comment]
@batgos DId you find any workaround?

**Comment by stellaLight** [comment]
You can set it manually by:
        this.datePicker.rightCalendar.month = moment(this.today);
        this.datePicker.leftCalendar.month = moment(this.today).subtract(1, 'month');
        this.datePicker.updateView();

**Comment by batgos** [comment]
Thanks it's work perfectly !
