### ISSUE TITLE
Change timezone of the datepicker

### ISSUE THREAD

**Issue by batgos** [fetrarij/ngx-daterangepicker-material#158]
Hello,
I would like to know if there is a way to change the timezone of the datepicker pls?
Because i'm using date at utc format and there is a jetlag between the both
Do there is a way to fix it please ?

**Comment by fetrarij** [comment]
Hello,

I think you can use [moment timezone](https://momentjs.com/timezone/) in the same way that we use moment locale in the project.

https://github.com/fetrarij/ngx-daterangepicker-material/wiki/How-to-change-calendar's-language%3F

**Comment by fetrarij** [comment]
I guess you have resolved this. Dont hesitate to reopen if you still need help :)

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/81137734-fad86a80-8f89-11ea-81ca-cc1d94e894d8.png)
`moment.tz.setDefault("America/New_York");`
change it global is the best solution

**Comment by roma2341** [comment]
> ![image](https://user-images.githubusercontent.com/16970990/81137734-fad86a80-8f89-11ea-81ca-cc1d94e894d8.png) `moment.tz.setDefault("America/New_York");` change it global is the best solution

It's sad that the author of the library doesn't know about injection tokens
