### ISSUE TITLE
Select end-date first in custom range

### ISSUE THREAD

**Issue by batgos** [fetrarij/ngx-daterangepicker-material#159]
Hi,
I would like to know if it's possible in custom range selection to have the choice to pick-up end-date first and not always start-date first please?
Could be more practical to use i think

**Comment by nathanvenezia** [comment]
up

**Comment by fetrarij** [comment]
Hello, until now that 's not possible

**Comment by batgos** [comment]
Hi, 
Do you plan to do it ? Or it's not a priority ?
