### ISSUE TITLE
Cannot read property 'every' of undefined 

### ISSUE THREAD

**Issue by ElHombreSinNombre** [fetrarij/ngx-daterangepicker-material#162]
The problem is simple: When i load ranges in daterangepicker return 

> Cannot read property 'every' of undefined
>     at DaterangepickerComponent.push

The code is

```
   ngOnInit() {
     AdminLTE.init();
     moment.locale("es");
     this.graph = "2";
     this.selected = {
       startDate: moment(this.start),
       endDate: moment(this.endFormat)
     };
     this.id = this.route.snapshot.paramMap.get("id");
     if (this.id) {
       this.graphCtrl.getMeter(this.id).subscribe(
         response => {
           this.ultimoValor = response["body"]["ultimoDatoConocido"];
           this.ultimoValorCierre = response["body"]["ultimoDatoCierreMes"];
           this.consumoMediaDiaria = response["body"]["consumoMedioDiario"];
           this.consumoMediaMensual = response["body"]["consumoMedioMensual"];
           this.consumoUltimoMes = response["body"]["consumoUltimoMes"];
           this.alertas = response["body"]["alarmasActivas"];
           this.contador = response["body"]["resumenDatameter"]["contador"];
           this.datameterId = response["body"]["resumenDatameter"]["id"];
           this.config();
         },
         error => {
           console.log(error);
         }
       );
     }
   }
 
   config() {
  this.ranges = {
       Hoy: [moment(), moment()],
       Ayer: [moment().subtract(1, "days"), moment().subtract(1, "days")],
       "Últimos 7 días": [moment().subtract(6, "days"), moment()],
       "Últimos 30 días": [moment().subtract(29, "days"), moment()],
       "Este mes": [moment().startOf("month"), moment().endOf("month")],
       "Mes pasado": [
         moment()
           .subtract(1, "month")
           .startOf("month"),
         moment()
           .subtract(1, "month")
           .endOf("month")
       ]
     };
 }
```

So: What is wrong in this code?

**Comment by Marceel13** [comment]
i've got the same problem, whe i set the ranges and then the customRangeLabel, whe i add custom ranges it works fine.

 ```
<input type="text" [showCustomRangeLabel]="true" [linkedCalendars]="true" ngxDaterangepickerMd
            [autoApply]="true" [ranges]="ranges" [locale]="localeOptions" [(ngModel)]="model">

```
```

  this.translate.get(['time.today', 'time.yesterday', 'time.last7', 'time.last30', 'time.this_month', 'time.last_month', 'time.custom',]).subscribe(
      (results: string[]) => {
        this.ranges = {
          [results['time.today']]: [moment(), moment()],
          [results['time.yesterday']]: [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          [results['time.last7']]: [moment().subtract(6, 'days'), moment()],
          [results['time.last30']]: [moment().subtract(29, 'days'), moment()],
          [results['time.this_month']]: [moment().startOf('month'), moment().endOf('month')],
          [results['time.last_month']]: [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        };
        this.localeOptions = {
          customRangeLabel: results['time.custom']
        }
      },
      (error: any) => {
        console.error("TODO: error translations");
      }
    );
```

**Comment by fetrarij** [comment]
hello @ElHombreSinNombre @Marceel13 ,  I have tested from the latest version, and I dont have an issue. Could  you give more info to reproduce the issue? how is your html? full typescript?

**Comment by tamimjabban** [comment]
> i've the same problem, when i set the ranges and then the customRangeLabel, when i add only custom ranges it works fine.
> 
> ```
> <input type="text" [showCustomRangeLabel]="true" [linkedCalendars]="true" ngxDaterangepickerMd
>            [autoApply]="true" [ranges]="ranges" [locale]="localeOptions" [(ngModel)]="model">
> ```
> 
> ```
> 
>   this.translate.get(['time.today', 'time.yesterday', 'time.last7', 'time.last30', 'time.this_month', 'time.last_month', 'time.custom',]).subscribe(
>       (results: string[]) => {
>         this.ranges = {
>           [results['time.today']]: [moment(), moment()],
>           [results['time.yesterday']]: [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
>           [results['time.last7']]: [moment().subtract(6, 'days'), moment()],
>           [results['time.last30']]: [moment().subtract(29, 'days'), moment()],
>           [results['time.this_month']]: [moment().startOf('month'), moment().endOf('month')],
>           [results['time.last_month']]: [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
>         };
>         this.localeOptions = {
>           customRangeLabel: results['time.custom']
>         }
>       },
>       (error: any) => {
>         console.error("TODO: error translations");
>       }
>     );
> ```

Were you able to get this to work? I'm having the same problem where if I use a translated value for `customRangeLabel`, I get the `Cannot read property 'every' of undefined` error. Thank you!

**Comment by tamimjabban** [comment]
@fetrarij Hi. Can you take another look at this please? I've having the same issue, and it seems that the `customRangeLabel` is not being updated when there's a translation change. Check this out; the following is when the language (Arabic) changed to another (English), and all the labels changed except the `customRangeLabel`.
![image](https://user-images.githubusercontent.com/8569316/70389141-8397ae00-19cc-11ea-9208-0d459748fcad.png)

**Comment by musabhusaini** [comment]
@fetrarij, we're running into this issue as well. I have been able to narrow the trigger down to changing `locale.customRangeLabel` while `showCustomRangeLabel` is set to `true`. See this [StackBlitz](https://angular-bhjj8t.stackblitz.io) for a simplified example.

**Comment by fetrarij** [comment]
This should be fixed with the latest version v2.1.10

**Comment by musabhusaini** [comment]
Thanks for the quick turnaround!

**Comment by dentkachuk** [comment]
I have the same issue, it happened when the selected range did not consist of predefined ranges and related to the "Custom range".
"moment": "^2.29.1",
"moment-timezone": "^0.5.32",
"ngx-daterangepicker-material": "^4.0.1",
