### ISSUE TITLE
Unable to override default styles of the daterange picker

### ISSUE THREAD

**Issue by Syeda-Urooj-Fatima** [fetrarij/ngx-daterangepicker-material#169]
I've been wanting to customize the daterange picker by overriding the CSS styles using:
_.md-drppicker {
    background-color: $grey-31 !important;
}_
The style isn't getting overriden.

**Comment by diamantisufi** [comment]
Try putting that in the main css/scss file and use !important.

**Comment by fetrarij** [comment]
As @diamantisufi says, put your style in the main style (style.css or style.scss).
This is the related issue with the fix so I'm closing this.
https://github.com/fetrarij/ngx-daterangepicker-material/issues/60
