### ISSUE TITLE
Applied range does not have 'active' class

### ISSUE THREAD

**Issue by abzats** [fetrarij/ngx-daterangepicker-material#17]
When you apply a range filter and re-open popup again "applied" range should be marked some way (e.g. with class 'active', like it is on jQuery version), but it is not.

**Comment by fetrarij** [comment]
Hello, it does. Unless with custom ranges, do you mean with custom ranges?

**Comment by abzats** [comment]
Yes, at least with custom ranges. But the same happen even on your "demo" examples.

**Comment by fetrarij** [comment]
Thank  you for reporting. v1.1.2 is up.
