### ISSUE TITLE
input mask for daterange

### ISSUE THREAD

**Issue by Cobr3n** [fetrarij/ngx-daterangepicker-material#179]
Hello
1) can i add input mask for textfield ?
2) after change input field, carbage in console 
![image](https://user-images.githubusercontent.com/25749976/62617551-55ca2c00-b93c-11e9-9d44-7acd342d50c4.png)

**Comment by fetrarij** [comment]
Hello, I really dont undestand what you want to accomplish.

**Comment by Cobr3n** [comment]
thanks we update packege and repair it)))) sorry for my perfect english )
