### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by jbanyer** [fetrarij/ngx-daterangepicker-material#181]
Hi there,

Thanks for making this useful component. I'm upgrading my project from Angular 6 to 8 and I get this error in the browser:

```NullInjectorError: No provider for LocaleService!```

I tried a few things but couldn't make it work.

Are there plans to support Angular 8?

Cheers

**Comment by fetrarij** [comment]
Hello.

This should work with angular 8 but maybe missed the change in importing the module.. take a look on readme, you should use forRoot()

**Comment by jbanyer** [comment]
Thanks @fetrarij - that fixed it.

You might like to update the README, which says: "This plugin is compatible with Angular2, Angular4, Angular5 and Angular6.". That did discourage me from investigating the problem further.

**Comment by fetrarij** [comment]
@jbanyer yes will update the readme. Thanks
