### ISSUE TITLE
Fails with Ivy

### ISSUE THREAD

**Issue by gidon-handler** [fetrarij/ngx-daterangepicker-material#185]
Great Plugin.

Unfortunately, fails in new Angular (Ivy).
Before long all new and **existing**  Angular projects will be moving to the (better) Ivy compiler.

Getting the common error: [ngClass]...[ngIf]...[ngFor]...ect.. not a know property of div.
(For some reason using the --prod flag works in build and serve)

Are you aware of the issue?
Is there a solution?

**Comment by fetrarij** [comment]
Hello @gidon-handler . Thanks for the report. I will definetely look into this

**Comment by gidon-handler** [comment]
That would be much appreciated.
P.s. Time is of the essence.

**Comment by gidon-handler** [comment]
Any word one this issue?

**Comment by Timebutt** [comment]
@gidon-handler: the new `3.0.0` releases definitely addresses this issue. Can you verify and close this issue if that's the case?

**Comment by gidon-handler** [comment]
@Timebutt: working now with 2.2.0. Probably because of the ngcc.

**Comment by Timebutt** [comment]
Great! Would be nice if you can close this issue for housekeeping then ;)
