### ISSUE TITLE
Open datepicker from button issue

### ISSUE THREAD

**Issue by masteruser20** [fetrarij/ngx-daterangepicker-material#188]
I would like to open datepicker form from the button, but nothing happend after clicked on button.

There is a simulation:
https://stackblitz.com/edit/angular-sfah71

**Comment by fetrarij** [comment]
Hello @masteruse20,

Take a look on the demo's sources https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.html

You should add `ngx-daterangepicker-action` as class in your button.
