### ISSUE TITLE
Last month doesn't adhere to min and max values?

### ISSUE THREAD

**Issue by praveenpuglia** [fetrarij/ngx-daterangepicker-material#19]
I am using presets and have a preset called 'Last Month' that looks like this.
```ts
export const LAST_MONTH: DateRangePreset = {
  name: 'Last Month',
  range: [
    moment()
      .subtract(1, 'month')
      .startOf('month'),
    moment()
      .subtract(1, 'month')
      .endOf('month')
  ]
};
```
I have this construct for internal purposes and just send the `range` bit to ngx-daterangepicker-material.

This doesn't seem to be following the minDate and maxDate settings. I have another preset for `Last 30 Days` which seems to be working fine. 

```ts
export const LAST_30_DAYS: DateRangePreset = {
  name: 'Last 30 Days',
  range: [moment().subtract(30, 'days'), moment().subtract(1, 'days')]
};
```

### Last Month
![image](https://user-images.githubusercontent.com/313363/42445332-6ea06826-8390-11e8-9814-25c9cff30e6b.png)

### Last 30 Days
![image](https://user-images.githubusercontent.com/313363/42445342-7d61887c-8390-11e8-8eeb-d4ffc98f8414.png)

**Comment by fetrarij** [comment]
Hello, thank  you for reporting. Will fix this :)

**Comment by praveenpuglia** [comment]
## Further analysis.
So this case arises when the start and end dates are both less than the min date. in that case, last month or any other range doesn't make any sense. Ideally the option should not even be enabled because those dates don't exist based on restrictions.

Can we somehow disable a preset option if...
1. start and end dates are both less than min date
2. start and end dates are both more than the max date?

**Comment by fetrarij** [comment]
@praveenpuglia v1.1.3 is up. Thank you

**Comment by praveenpuglia** [comment]
Thanks so much for being such prompt! :)
