### ISSUE TITLE
Angular 8 ViewChild error

### ISSUE THREAD

**Issue by heikopiirme** [fetrarij/ngx-daterangepicker-material#191]
ERROR in ../node_modules/ngx-daterangepicker/src/ngx-daterangepicker/ngx-daterangepicker.component.ts:69:6 - error TS2554: Expected 2 arguments, but got 1.

69     @ViewChild('fromInput') fromInput: ElementRef;
        ~~~~~~~~~~~~~~~~~~~~~~


The static option in ViewChild is mandatory as of right now.

**Comment by heikopiirme** [comment]
Im stupid

**Comment by Henryisthebest** [comment]
@heikopiirme  - how did you fix it?
