### ISSUE TITLE
isinvalidDate 

### ISSUE THREAD

**Issue by sampath3797** [fetrarij/ngx-daterangepicker-material#193]
Thanks for providing ngx-daterangepicker. 

Iam facing problem while using isinvalidDate function in my component.  
I'm not able to use my components variable inside this function,  it says undefined. 

how to do this? 

I want some logic inside isinvalidDate to disable some dates based on some dynamic values in the variables in my component. 

please help me in this regard.

**Comment by nabilberrada98** [comment]
I had the same issue, it gives undefined because "this" inside isinvalidDate function refers to the ngx-daterangepicker, so my workaround this issue is i declared the attribute i needed as static , i know it's not the best thing to do but at least it worked, if you guys have a better suggestion i'am open to it

**Comment by fetrarij** [comment]
@sampath3797 @nabilberrada98 hello,  provide your code please.
How did you defined the isInvalidDate ?
something like:

```
  isInvalidDate = (m: moment.Moment) =>  {
    return this.invalidDates.some(d => d.isSame(m, 'day') );
  }
```

**Comment by sampath3797** [comment]
> @sampath3797 @nabilberrada98 hello, provide your code please.
> How did you defined the isInvalidDate ?
> something like:
> 
> ```
>   isInvalidDate = (m: moment.Moment) =>  {
>     return this.invalidDates.some(d => d.isSame(m, 'day') );
>   }
> ```

Yes , similar to this values from api call mentioned below

 this._persService.getInvalidDates(this.EmpId)
       .subscribe(
         unAvailableDates => {
          this.invalidDates = unAvailableDates; 
          },
         error => {this.handleServiceCallError(error), this._isLoading = false;}
       );
	   
isInvalidDate(date){
    
  if(this.invalidDates.indexOf(date._d)>-1)
  {
    console.log('matched')
    return true;
  }
  return false;
}

_1.    this.invalidDates  is not accessible inside isInvalidDate.

2.   Similarly instead of returning boolean value if we are able to send custom css and tooltip (just like isCustomDate returns custom css) above those dates it will be more useful. 
Reason behind those dates unavailable for selection eg:- any closed holiday or maintenance day on particular dates. 

Thanks in advance_

**Comment by fetrarij** [comment]
Hello, sorry for the late reply (little busy :) )
1. your code should be something like this:
```
this._persService.getInvalidDates(this.EmpId)
.subscribe(
unAvailableDates => {
  this.invalidDates = unAvailableDates.map(i => moment(i));
},
error => {this.handleServiceCallError(error), this._isLoading = false;}
);

isInvalidDate(date){
  return this.invalidDates.some(d => d.isSame(m, 'day') );
}```

2. I am adding 'invalid' class for all invalidDates

**Comment by sampath3797** [comment]
Thank you very much

**Comment by sampath3797** [comment]
Thanks for providing great datepicker . 

### **_I modified ngx-daterangepicker-material.js file to implement tooltip to show holiday or event names by returning custom date class with tooltiptext.  (just like beforeshowday in jquery datepicker)._**

**will you please include in your code for both custom date and invalid date and update.**

////////in ngx-daterangepicker-material.js //////

///////line number 60 added property tooltiptextFrmApp/////////////////
this.tooltiptextFrmApp=[];   
////////////////////////////////////////////


/////////////////////near line number 1100////////////////////////
var isCustom = this.isCustomDate(calendar[row][col]);
                if (isCustom !== false) {
                    if (typeof isCustom === 'string') {
 var customCss=isCustom.split('-');     //splitting css class name and tooltiptext returned from app 
                                                             //customDate method
   var isCustom=customCss[0];            //setting css for custom date
  this.tooltiptextFrmApp[calendar[row][col]]=customCss[1];   //setting tooltiptext for custom date
    classes.push(isCustom);
                    }

///////////////////in template near line number 1311/////////////////////////////////////
////for left calendar
<span>
{{calendarVariables.left.calendar[row][col].date()}}

<span class='tooltiptext'>
{{tooltiptextFrmApp[calendarVariables.left.calendar[row][col]]}}
</span>

</span>

////for right calendar
<span>
{{calendarVariables.right.calendar[row][col].date()}}

<span class='tooltiptext'>
{{tooltiptextFrmApp[calendarVariables.right.calendar[row][col]]}}
</span>

</span>

////////////////////////////////////////////////////

/////////following styles.css in my project//////////////////////////

.ch{
  background-color: coral;
}

.tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: black;
  color: #fff;
  text-align: center;
  padding: 5px 0;
  border-radius: 6px;

  /* Position the tooltip text - see examples below! */
  position: absolute;
  z-index: 1;
}

/* Show the tooltip text when you mouse over the tooltip container */
.ch:hover .tooltiptext {
  visibility: visible;
}
/////////////////////////////////////////////////////////////

This above implementation working perfectly in development which shows tooltiptext as sampath on mouseover of date 15 Jan 2020.
![image](https://user-images.githubusercontent.com/44496687/72370804-037e0a00-3729-11ea-85c8-f8728de40798.png)

**### _but when i build app for production
the tooltiptext span in template was missing in mainbundle.js generated in my angular project and the tooltip was not showing in production_** 

will you please update the code to work in production also.
