### ISSUE TITLE
duplicate ranges in both calendars

### ISSUE THREAD

**Issue by luguiant** [fetrarij/ngx-daterangepicker-material#199]
I currently use the ranges component in an important project, I must use 4 custom ranges:

- last week.
- last month.
- Last three months.
- Last six months.

Today, November 20, 2019, I have an error in which if I select the range of the last week, this range is shown in both calendars.

I have a slight suspicion that this occurs because the range is contained within the current month, which would imply that it could occur in the range of the last month, this when the date is 30 or 31, if someone already has a solution for this error, I would appreciate it if you give me a hand, since I need to solve this problem urgently, I leave the configuration code of my inputHtml:

`  <input matInput type="text" 
          id="rangeCalendarInput" readonly 
          ngxDaterangepickerMd 
          [(ngModel)]="selected"
          (ngModelChange)="modelChangeValue($event)"
          [minDate]="month6Date"
          [maxDate]="todayDate"
          [customRangeDirection]="true"
          [showCustomRangeLabel]="true" 
          [alwaysShowCalendars]="true"
          [keepCalendarOpeningWithRange]="true" 
          [ranges]="ranges"
          startKey="start" endKey="end" [lockStartDate]="false"
          [linkedCalendars]="false" [showCancel]="true" />`

leave the LinkedCalendars option in false, this is because the navigation arrows are not activated for the 6 month range if LinkedCalendars = true, again I ask for help with the error of the duplicate months, it really is something of incredible urgency for me and I must find a solution for this immediately

bug related to:
https://github.com/fetrarij/ngx-daterangepicker-material/issues/180

**Comment by fetrarij** [comment]
@luguiant your TS file?
