### ISSUE TITLE
prev & next icons are missing in corner case

### ISSUE THREAD

**Issue by Ratikant01** [fetrarij/ngx-daterangepicker-material#2]
Thanks for this great project!
I found it does not show the <, > icons when I set minDate (say 2017-May-22) and maxDate (say 2018-May-21); When I use "from" date calendar and go to previous months it shows the < icon, but once it reaches May (in this case), it does not show any icons in both the calendars - so we cannot go to any other months. Issue could be it does not consider year when comparing months.

![image](https://user-images.githubusercontent.com/5038421/40301455-d089be50-5d09-11e8-9e0b-077e0ddbf358.png)

**Comment by fetrarij** [comment]
Hello @Ratikant01 ,

Could you **fork** , **update**  and **save** this editor with your issue: https://stackblitz.com/edit/ngx-daterangepicker-material-uwpplc so I can understand how to reproduce the issue please?

Thanks

**Comment by Ratikant01** [comment]
Thanks, I tried to fork but could not do so.. 
Here is the code.

` <input type="text" id="dateRange" data-e2e-id="dateRange" name="dateRange"
                   ngxDaterangepickerMd [autoApply]="true"
                   [locale]="{applyLabel: 'Apply', format: 'YYYY/MM/DD'}"
                   [minDate]="getMinDate()" [maxDate]="getMaxDate()"
                   [(ngModel)]="filterModel.dateRange"
                   startKey="fromDate" endKey="toDate"
                   required/>`

`getMinDate(): any {
 return this.moment().subtract(1, 'years').add(1, 'days');
}
  getMaxDate(): any {
    return this.moment();
  }`

Hope this would help.

**Comment by fetrarij** [comment]
@Ratikant01 , yes this is the behaviour and I could reproduce your issue
https://ngx-daterangepicker-material-rfvv3o.stackblitz.io

**Comment by Ratikant01** [comment]
Thank you very much!!
