### ISSUE TITLE
Is there a way to know which preset range was selected?

### ISSUE THREAD

**Issue by praveenpuglia** [fetrarij/ngx-daterangepicker-material#20]
I am creating a component where I am gonna be using two of these range pickers and I want to know which range I have selected in the first so I can programmatically change the range on the second one and vice versa. 

Currently, I didn't find a way to figure out which range is selected be it a custom one or one of the supplied presets.

Is there a way to do this ?

**Comment by fetrarij** [comment]
Could you give more detail? For my understand you want to know which datepicker are changed? 
=> by the ngModel and ngModelChange

**Comment by praveenpuglia** [comment]
If I selected Today in the ranges section, I want to know I selected Today. Because of two reasons.

1. Sometimes we don't just wanna show dates we might want to show the NAME of the range. So if I select Today, it should show "Today" but select the today range. 

2. To take decisions. Example 
If I can know I selected "Today" in one calendar, I can then decide to programmatically supply the necessary date range (say "Yesterday") in a different calendar. Good for comparisons.

**Comment by fetrarij** [comment]
What if we send from an event the label's range clicked? something like `(customRangeSeleced)="..."`

**Comment by fetrarij** [comment]
that's what I thought too. Some dont like to display the label some yes...would have an option maybe

**Comment by praveenpuglia** [comment]
Yeah.. If you can show the dates for custom and the preset names for the other presets that would be cool. Via an option. :)

**Comment by praveenpuglia** [comment]
So I am thinking this is how it should work.
- the change event should pass me an object with the name of the range and the range. So if I select Today, it should send me `{name: 'Today', range: [Moment, Moment]}` or equivalent. 

This way, it can handle all cases in a general way.

**Comment by fetrarij** [comment]
@praveenpuglia with v1.1.4 released, you can now use:

### \(rangeClicked)

 >Fired when clicked on range, and send an object with range label and dates value, eg:  `{label: 'This Month', dates: [Moment, Moment]}`

**Comment by praveenpuglia** [comment]
@fetrarij Awesome! thanks so much! :)
