### ISSUE TITLE
Problem with Custom range selector

### ISSUE THREAD

**Issue by enigma119** [fetrarij/ngx-daterangepicker-material#202]
The problem is when i'm trying to bind the range of selected date i get " undefined"
i tried the "2 way data binding" with ngModel and also tried to console log the selected value but aint got nothing

**Comment by fetrarij** [comment]
Your actual code?

**Comment by enigma119** [comment]
<div class="page-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-block">
                    <div class="j-wrapper wrapper-640">
                        <form class="j-pro" id="j-pro" novalidate #f=ngForm>
                            <div class="j-content">


                                <div class="row" id="entrepogage_content">
                                    <div class="col-md-12 col-lg-12">
                                        <h4 class="sub-title">Entrepogage</h4>
                                        <br>

                                        <div class="col-md-12 col-lg-12">
                                            <div id="entreposage">
                                                <div class="form-group row">
                                                    <div class="col-md-6 col-lg-6">
                                                        <label class="j-label">Nature Marchandise</label>
                                                        <div class="j-input">
                                                            <input type="text" id="merchandiseType"
                                                                name="merchandiseType" [(ngModel)]="merchandiseType">
                                                        </div>
                                                    </div>

                                                    <div class="col-md-6 col-lg-6">
                                                        <label class="j-label">Choisir date </label>
                                                        <input type="text"
                                                        ngxDaterangepickerMd
                                                        [(ngModel)]="selectedRange"
                                                        [showCustomRangeLabel]="true"
                                                        [alwaysShowCalendars]="true"
                                                        [ranges]="ranges"
                                                        [linkedCalendars]="true"
                                                        [showClearButton]="true"

                                                        placeholder="Choisir date.../">
                                                        <button class="btn btn-warning" (click)="test()">Enregistrer Date</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                                {{selectedRange}}
                                                {{merchandiseType}}
                                        <br>
                                        <br>
                                        <div class="gap-top-45 gap-bottom-45"></div>
                                    </div>
                                </div>

                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

**Comment by enigma119** [comment]
import { Component,  } from '@angular/core';
import { NgForm } from '@angular/forms';

import * as moment from 'moment';
import * as localization from 'moment/locale/fr';
moment.locale('fr', localization);




@Component({
    selector: 'app-testDate',
    template: require('./testDate.html')
})
export class TestDateComponent {

    merchandiseType: string;
    selectedRange: any;

    alwaysShowCalendars: boolean;
    ranges: any = {
      'Today': [moment(), moment()],
      'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
      'Last 7 Days': [moment().subtract(6, 'days'), moment()],
      'Last 30 Days': [moment().subtract(29, 'days'), moment()],
      'This Month': [moment().startOf('month'), moment().endOf('month')],
      'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
    };



    constructor() {
        this.alwaysShowCalendars = true;
    }


    test() {
        console.log('Selected Range  ====>', this.selectedRange);
      }


}

**Comment by enigma119** [comment]
HI sir! 
i finnaly got the solution 
Instead of using Ngmodel to get the value, i used (change) event to get the date range 

bellow is my code 





<input type="text" ngxDaterangepickerMd [showCustomRangeLabel]="true" [alwaysShowCalendars]="true" [ranges]="ranges"
                                                            [linkedCalendars]="true" [showClearButton]="true" [timePicker]="true" [timePickerSeconds]="true"
                                                            [timePickerIncrement]="15" [timePicker24Hour]="true" [locale]="{format: 'DD/MM/YYYY HH:mm:ss', firstDay: 1}"
                                                            (change)="choosedDate($event)" placeholder="Choisir date...">

**Comment by adars99** [comment]
@enigma119 Thanks for providing the solution.

**Comment by fetrarij** [comment]
Thanks , but you should take a  look on the demo https://github.com/fetrarij/ngx-daterangepicker-material/tree/master/demo/src/app/custom-ranges
