### ISSUE TITLE
Doesn't work with moment 2.24.0

### ISSUE THREAD

**Issue by chiefchef** [fetrarij/ngx-daterangepicker-material#203]
New import statements should be changed:

**OLD:**
`import * as _moment from 'moment';`

**NEW:**
`import moment from 'moment';`

The moment var and const declarations should be removed.

Can someone confirm this is an issue. We get errors when we are using this package in our system and the issues are resolved if I make these edits in your package.

**Comment by fetrarij** [comment]
@chiefchef hello,
There are no [docs](https://momentjs.com/docs/#/use-it/typescript/) saying the old and the new way for this. Check you typescript version and follow this https://momentjs.com/docs/#/use-it/typescript/
