### ISSUE TITLE
Doesn't work with other date lib for eg.dayjs .is is moment Lib is must?

### ISSUE THREAD

**Issue by virendra-180kumar** [fetrarij/ngx-daterangepicker-material#205]

**Comment by virendra-180kumar** [comment]
I like to use https://www.npmjs.com/package/dayjs lib because of the small size.
I tried to implement with this lib, but date calendar isn't working properly

**Comment by fetrarij** [comment]
moment.js is a must from starting the project

**Comment by gjsmith66** [comment]
I have a fork that supports dayjs at https://github.com/gjsmith66/ngx-daterangepicker-material-dayjs
