### ISSUE TITLE
Incorrect calendar behavior when choosing a custom range within one month

### ISSUE THREAD

**Issue by YShakhrai** [fetrarij/ngx-daterangepicker-material#206]
Hi @fetrarij ,
I faced an issue: 
- on calendar open we see current month (left - December 2019) and next month (right - January 2020);
- on clicking custom range label (with startDate and endDate in same month) right calendar is switching (in my case to January 2019).

If I create range with next 30 days, as example, it works fine.

I reproduced it in stackblitz:
https://stackblitz.com/edit/ngx-daterangepicker-material-qyhfe1

Is there any way to fix or avoid this incorrect switch?
Thank you!

**Comment by coreysherman-accesso** [comment]
I am able to recreate this issue as well..  It only seems to happen if the selected range starts and ends within December.

**Comment by piero-b** [comment]
I'm also having this issue so would be great to get it fixed.

**Comment by coreysherman-accesso** [comment]
Your fix is working perfectly, thank you!

**Comment by YShakhrai** [comment]
@fetrarij Thanks a lot!
