### ISSUE TITLE
Calendar is upsite down

### ISSUE THREAD

**Issue by christosv94** [fetrarij/ngx-daterangepicker-material#207]
For some reason even when I sue the simplest date picker, the first month calendar appears upside down. Any thoughts on this?

![image](https://user-images.githubusercontent.com/22153938/71077937-4c6d8d80-2180-11ea-8cb3-79c9c8235ebb.png)

**Comment by fetrarij** [comment]
I have never encountered this problem, maybe a CSS overlay?

**Comment by christosv94** [comment]
yea it was a css rule in another part of the project, overwriting it, thanks
