### ISSUE TITLE
Showing correct but variables are one day past

### ISSUE THREAD

**Issue by sabloger** [fetrarij/ngx-daterangepicker-material#210]
I use it in this way:
`
filterValues={
      depart_dates: {
        startDate: moment(),
        endDate: moment().add(120, 'days')
      }
}
`
`
<input type="text" ngxDaterangepickerMd [(ngModel)]="filterValues.depart_dates"
               (change)="onControlsChange('date')" class="form-control" dateLimit="120"/>
`

I set "moment()" for current date, but it shows correctly but when I see at my variables those are one day before what are showing!
for example:
it shows: 2019-12-31
variable: 2019-12-30

why?

**Comment by sabloger** [comment]
Sorry I closed it accidentally

**Comment by sabloger** [comment]
When I put `matInput` attribute in the input definition (I saw in examples) showing problem was fixed, But the variable are still 1 day before what is showing

**Comment by DoanVanThuong** [comment]
Maybe it can relative to startDate, endDate

**Comment by sabloger** [comment]
I think it is because of timezone, because it sets the variable about 4 hours before the selected day!

**Comment by fetrarij** [comment]
you can use moment-timezone to fix this
