### ISSUE TITLE
Date range picker is not openning when using this.pickerDirective.open(e);

### ISSUE THREAD

**Issue by rcogal** [fetrarij/ngx-daterangepicker-material#212]
Package version:  "ngx-daterangepicker-material": "^2.1.11"
Description:

It's not opening when I try to apply the sample code where the date range picker opens when clicking the button

**Comment by rcogal** [comment]
I found the workaround. I have to put the open method inside the settimeout

setTimeout( () => {
his.pickerDirective.open($event);
})


I am not sure why it's not loading but maybe because there were setTimeout on the daterangedirective when calculating the position as to why it creates a conflict?

**Comment by fetrarij** [comment]
We dont need it in the [demo](https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.ts) .
