### ISSUE TITLE
on page load today date is not working

### ISSUE THREAD

**Issue by ramakrim** [fetrarij/ngx-daterangepicker-material#215]
Hi,
say my
<input 
                        type="text"
                        ngxDaterangepickerMd
                        [(ngModel)]="selectedDate"
                        [showCustomRangeLabel]="true"
                        [showRangeLabelOnInput]="true"
                        [alwaysShowCalendars]="true"
                        [ranges]="ranges"
                        [maxDate]="maxDate"
                        placeholder="Choose date" 
                        (change)="changeDate($event)"/>

whereas in TS
selectedDate = { startDate: moment(), endDate: moment() };

i am supposed to get
startDate: 2020-01-20T18:30:00.000Z
endDate: 2020-01-21T18:29:59.999Z

but i am getting wrong value
startDate: 2020-01-21T11:08:19.747Z
endDate: 2020-01-21T11:08:19.747Z

due to which the data is not being loaded since the startDate and endDate are same.

For the refrence please check the link below
https://fetrarij.github.io/ngx-daterangepicker-material/custom-ranges

where the default date set is yesterday and the model data of startDate and endDate is same.

In the screenshot below please check the model data which is highlighted  (start and end date are same).
![DateIssue](https://user-images.githubusercontent.com/26565220/72801337-4bdc8100-3c6f-11ea-8872-c738a275cfcd.JPG)

Thanks

**Comment by fetrarij** [comment]
hello @ramakrim ,

if you want it init your value with something like:

this.selected = {
      startDate: moment().subtract(1, 'days').set({hours: 0, minutes: 0}),
      endDate: moment().subtract(1, 'days').set({hours: 23, minutes: 59})
 };
