### ISSUE TITLE
Setting firstDay to 7 causes months that begin on Sunday to display NaN for each day

### ISSUE THREAD

**Issue by joe-tyler** [fetrarij/ngx-daterangepicker-material#218]
Steps to replicate:
1. Change the [locale] to [locale]="{ firstDay: 7}"
2. Use the control and go to a month that starts on a Sunday like March 2020.  The dates for the beginning of March appear fine at the bottom of the February calendar, but switching over to March shows NaN for each day.
<img width="551" alt="Screen Shot 2020-01-28 at 9 21 46 AM" src="https://user-images.githubusercontent.com/34774650/73271998-a3b74280-41af-11ea-976a-3b9a2d2e1b91.png">
This is how March 2020 displays:
<img width="549" alt="Screen Shot 2020-01-28 at 9 22 16 AM" src="https://user-images.githubusercontent.com/34774650/73272033-b5004f00-41af-11ea-847b-647c2399fbd8.png">

Thanks!

**Comment by fetrarij** [comment]
@joe-tyler try with {firstDay: 0} this is for sunday

**Comment by joe-tyler** [comment]
Thanks!  It is working.
