### ISSUE TITLE
A range on the left isn't highlighted by default even if it matches the supplied range

### ISSUE THREAD

**Issue by praveenpuglia** [fetrarij/ngx-daterangepicker-material#22]
Say I supply an object with `{startDate:  moment(), endDate: moment()}` that matches the 'Today' range, it should be highlighted when the datepicker is opened for the first time. 

Currently the range names are only highlighted if someone clicked on them.

**Comment by praveenpuglia** [comment]
I am trying to get around this by creating a method that gets called on ngOnInit()

```js
    findActiveRange() {
      let ranges = Object.keys(this.ranges);
      let activeRange = ranges.filter( range => {
        const rangeMarkers = this.ranges[range];
        return rangeMarkers[0].isSame(this.startDate, 'day') && rangeMarkers[1].isSame(this.endDate, 'day');
      })[0];

      if(activeRange) {
        this.chosenRange = activeRange;
      } else {
        this.chosenRange = this.locale.customRangeLabel;
      }
    }
```

The HTML remains the same.

```html
<button type="button"
                    (click)="clickRange($event, range)"
                    [disabled]="disableRange(range)"
                    [ngClass]="{'active': range === chosenRange}">{{range}}</button>
```
The problem is that `this.startDate` and `this.endDate` are always initialized as today's date. I want to compare the range's dates to the one supplied by user via ngModel. How do I do that?

**Comment by fetrarij** [comment]
this is the hack https://github.com/fetrarij/ngx-daterangepicker-material/commit/2751a30a538f62aa5dbb28dde19f2026ebd24a1f

**Comment by praveenpuglia** [comment]
Awesome! :)
