### ISSUE TITLE
Easier to select single date and time while in range view

### ISSUE THREAD

**Issue by camillewall** [fetrarij/ngx-daterangepicker-material#232]
When selecting a date range I would like to be able to set the time before both the start and end date are selected. By looking at the code this seems quite easy, remove the disabled check looking to see if the end date is selected.

Similar to this sometimes when selecting a date range I want to be able to select a single date. Currently a user must double click on the date to set it as the start and end date. It would be nice if when only one date was selected the time ranges would be available and used when the apply button is pressed. Right now if only the start date is selected it makes both the start and end the same date time.

I am currently using version 2.1.10.

**Comment by fetrarij** [comment]
:+1:
