### ISSUE TITLE
[FEATURE REQUEST] Migrate from Moment.js to another lib / using DateAdapter

### ISSUE THREAD

**Issue by niklissad** [fetrarij/ngx-daterangepicker-material#234]
Hello all

I really like this datepicker but I got stucked when I added moment.js to my project and saw how it increased my bundle. I tried to use `moment-mini` but build was no success. so unfortunately I can't use it for production - the bundle is very huge (just look at [webpack bundle analyzer](https://gist.github.com/niklissad/2ad81b3ce886ce8c68a4ed74f023754b))

I found some articles about moment [Why you shouldn't use Moment.js...](https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js)

And plugin that would help to migrate [You-Dont-Need-Momentjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs)

The better thing would be to write Date Adapter which can connect datepicker to any date module/plugin

I can help (If you want) with migration

**Comment by insomniaTY** [comment]
Nice idea to have date-fns as dependency

**Comment by fetrarij** [comment]
Date-fns may be a good idea :)

**Comment by mrFll** [comment]
Great Idea. we also need the ability to use an alternative time library for our project. 
When do you plan to add this feature?

**Comment by fetrarij** [comment]
Hello, v5 is out and finally momentjs is replaced with dayjs.
