### ISSUE TITLE
Provision to add & highlight  new list of dates

### ISSUE THREAD

**Issue by udaysappa** [fetrarij/ngx-daterangepicker-material#239]
This is a feature request.

Can you please provide a date list place holder (Similar to invalid dates) and a css class to highlight those dates (like: firstMonthDayClass).

The reason behind to ask this feature is, this will help to show the dates which are already blocked by others. (Ex: To highlight the booked seats in a bus/movie). In this case we cannot use invalid dates list because, user cannot differentiate between invalid dates and the booked dates.

**Comment by fetrarij** [comment]
And what if you use isCustomDate @udaysappa , your function should return the class you want (string) for the date you want, then custom the class

**Comment by udaysappa** [comment]
@fetrarij : thanks for your response. Your suggestion worked.
