### ISSUE TITLE
select year error

### ISSUE THREAD

**Issue by boloboloda** [fetrarij/ngx-daterangepicker-material#247]
If maxDate is not set, selecting the largest year will give an error.
![image](https://user-images.githubusercontent.com/29855529/76949180-21dbce00-6943-11ea-95ea-0d4deeb99572.png)
![image](https://user-images.githubusercontent.com/29855529/76949121-0bce0d80-6943-11ea-823c-f04141b5ed30.png)

**Comment by MikeG96** [comment]
Same issue
