### ISSUE TITLE
MAT_DATE_LOCALE does not work for daterangepicker

### ISSUE THREAD

**Issue by akshaybhat30** [fetrarij/ngx-daterangepicker-material#249]
I am using MAT_DATE_LOCALE to set the date format in my application but it is not working on date range picker.

**Comment by fetrarij** [comment]
Hello, it doesnt depend on angular material, it's an independant component, if you want to change some locale try this https://github.com/fetrarij/ngx-daterangepicker-material/wiki/How-to-change-calendar's-language%3F
