### ISSUE TITLE
The year on January Title is for previous year.

### ISSUE THREAD

**Issue by Thanatos-elNyx** [fetrarij/ngx-daterangepicker-material#25]
https://fetrarij.github.io/ngx-daterangepicker-material/single-datepicker

If you start scrolling back the months, it goes from "Feb 2018" to "Jan 2017". 

I believe the issue is here in daterangepicker.component.html

<ng-container *ngIf="!showDropdowns || !calendarVariables.left.dropdowns">
		{{this.locale.monthNames[calendarVariables?.left?.calendar[1][1].month()]}}  {{ calendarVariables?.left?.calendar[0][0].format(" YYYY")}}
</ng-container>

{{ calendarVariables?.left?.calendar[0][0].format(" YYYY")}}
Is asking for the year of the first date in the top left of the calendar.
For January this date is usually a date in December.

Probable solution is to do the same thing as the Month, and get the 2nd date of the second row, which should always be in the same year as the current month:
{{ calendarVariables?.left?.calendar[1][1].format(" YYYY")}}

**Comment by fetrarij** [comment]
Hello, thanks for the report.
Good job finding this bug.
Would you do a PR?

**Comment by fetrarij** [comment]
And yes, [1][1] is the solution since [0][0] may could be the previoous month/year.
I was waiting for your PR but you didn't do.
I am fixing the bug with:  this single datepicker is not updating the right date value after selecting a date.
Please use the last version to have the fix.
And again, thank you for reporting

**Comment by Thanatos-elNyx** [comment]
I am new to github so I didn't know how to do a PR. :(
Thanks for the quick response though. :)

**Comment by fetrarij** [comment]
@Thanatos-elNyx should create PR again the main repo not yours ;)
https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

Dont hesitate to creating PR on future :)
