### ISSUE TITLE
popup doesn't spill over other elements

### ISSUE THREAD

**Issue by tylertucker202** [fetrarij/ngx-daterangepicker-material#250]
Thanks for making this available. This component is great! 

I've implemented it on my app argovis.colorado.edu. 

The calendar popup is confined to sidebar menu is a bit squished (see image attached)
![Screenshot from 2020-03-25 16-48-30](https://user-images.githubusercontent.com/4924229/77605432-f6b02c00-6eb8-11ea-816c-736ed6a3c3fe.png).
Is there any way we can get it to spill over horizontally so that it covers some of the map element?
I've tried altering the popup's style to
.md-drppicker {
  position: relative !important;
  z-index: 1000000;
}
in my main styles.css but it still is squished in the sidebar. Setting the position to absolute didn't work either. I used to use ng2-daterangepicker until today, and it spilled over.

Thank you for your help!

**Comment by tylertucker202** [comment]
I took another swing at this issue. I could get it to spill over with the css below. 

`
.md-drppicker.shown.drops-down-right {
    position: fixed;
}
`

**Comment by srinicoollife** [comment]
@tylertucker202 this solutions works for me too. thanks for sharing
