### ISSUE TITLE
this.selected = null; not working

### ISSUE THREAD

**Issue by CARIVASH** [fetrarij/ngx-daterangepicker-material#253]
I created a function named clear() like this: `clear(){ this.selected = null;} `, but when I press the button clear, just doesn't work.

**Comment by Timebutt** [comment]
Have you checked the [example](https://fetrarij.github.io/ngx-daterangepicker-material/simple) on how to implement a clear button? The example has a correctly working clear button, so I'm assuming you didn't bind `selected` correctly to the component.
