### ISSUE TITLE
How can I Construct isCustomDate function after a API call

### ISSUE THREAD

**Issue by NirmanNPS** [fetrarij/ngx-daterangepicker-material#256]
Hi,
I am new to this module and I need to construct the isCustomDate function after I subscribe some calendar data from backend. It would be a great help if you can advise how to construct the isCustomDate everytime I make the API call.

Thanks

**Comment by fetrarij** [comment]
Hello @NirmanNPS ,
Is there something you have tried?
You can take inspiration from [this demo](https://github.com/fetrarij/ngx-daterangepicker-material/blob/2c9bd87f2f4df614f0f1f193d2a268a198863cb6/demo/src/app/single-datepicker/single-datepicker.component.ts#L27)

May be you need to load your date from api and compare theses date in the isCustomDate function.

**Comment by NirmanNPS** [comment]
Thanks @fetrarij 
Yes, I am using the function to load different css classes. But it seems like the calendar component is loading with the function before the API returns the dates and once the API returns any date, the calendar view is not automatically refreshing with new isCustomDate. 
This is my isCustomDate function
@Input() data; //received from Parent component
  isCustomDate(date) {
    console.log('Inside custom Date => ', this.data);
    if (this.data) {
        const calendarDate = this.datePipe.transform(date._d, 'yyyy-MM-dd');
        const today = this.datePipe.transform(new Date(), 'yyyy-MM-dd');
        return this.data.filter(diarySlot => diarySlot.date === calendarDate)
                       .map(diarySlot => {
                          if (diarySlot.selected && !diarySlot.optimal) {
                            return 'selected';
                          } else if (!diarySlot.selected && diarySlot.optimal) {
                            return 'optimal';
                          } else if (diarySlot.selected && diarySlot.optimal) {
                            return 'optimal-selcted';
                          }
                       });
     }
  }

This is my template:
<ngx-daterangepicker-material (datesUpdated)="choosedDateTime($event)"
                              [linkedCalendars]="true"
                              [isCustomDate]="(isCustomDate)"
                              [locale]="{applyLabel: 'Done'}"
                              >
</ngx-daterangepicker-material>

I have also tried to run chageDetectionRef.detectChange() to re-render the calendar view but the view is not getting refreshed.
Any sort of help in this regard would be very much appreciated. 
Thanks
