### ISSUE TITLE
Build suddenly failing after your recent commits

### ISSUE THREAD

**Issue by RanojitMitra** [fetrarij/ngx-daterangepicker-material#259]
Currently, our project was using v2.2.0, daterangepicker was working fine.
At 3:09PM GMT, our build was successful, seven minutes later at 3:16PM GMT, the same build script starts failing. Is there any issues from your side, please help.
We have our deadlines soon and need to get this issue fixed.
The error comes in the step 'ng build --prod'
The error message is shown below:

ERROR in node_modules/ngx-daterangepicker-material/locale.service.d.ts:5:9 - error TS1086: An accessor cannot be declared in an ambient context.

5     get config(): LocaleConfig;
          ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.component.d.ts:59:9 - error TS1086: An accessor cannot be declared in an ambient context.

59     set locale(value: any);
           ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.component.d.ts:60:9 - error TS1086: An accessor cannot be declared in an ambient context.

60     get locale(): any;
           ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.component.d.ts:62:9 - error TS1086: An accessor cannot be declared in an ambient context.

62     set ranges(value: any);
           ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.component.d.ts:63:9 - error TS1086: An accessor cannot be declared in an ambient context.

63     get ranges(): any;
           ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.directive.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient context.

55     set locale(value: any);
           ~~~~~~
node_modules/ngx-daterangepicker-material/daterangepicker.directive.d.ts:56:9 - error TS1086: An accessor cannot be declared in an ambient context.

56     get locale(): any;
           ~~~~~~

**Comment by fetrarij** [comment]
hello @RanojitMitra 

use the v2.2.0, in package.json set "ngx-daterangepicker-material": "2.2.0"

**Comment by RanojitMitra** [comment]
that was already there still it was failing in pipelines, I added a task "npm install ngx-daterangepicker-material@2.2.0" in my pipeline before npm install and it worked out.

**Comment by RanojitMitra** [comment]
I had  "ngx-daterangepicker-material": "^2.2.0" in package.json, so it was failing. Removing ^ worked as well. Thank You.. :-D

**Comment by nishit321** [comment]
Thanks @RanojitMitra
