### ISSUE TITLE
startKey and endKey is not used at all

### ISSUE THREAD

**Issue by dez1729** [fetrarij/ngx-daterangepicker-material#261]
Breaking change since v3.0.0

startKey and endKey no longer works in any way. Similar to #227 but also does not get used at initialization as well as events.

The full demo also reflects this: it shows the input in startKey and endKey in the template but the component actually uses startDate and endDate.

v2.1.0 still work with startKey and endKey being recognized.

**Comment by fetrarij** [comment]
Hello, thanks for reporting. Will fix this.

**Comment by fetrarij** [comment]
this should be fixed with 3.0.2
