### ISSUE TITLE
ERROR in Cannot read property 'map' of undefined on npm start

### ISSUE THREAD

**Issue by edditrana** [fetrarij/ngx-daterangepicker-material#265]
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect               0.803.21
@angular-devkit/build-angular       0.803.24
@angular-devkit/build-optimizer    0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core                      8.3.21
@angular-devkit/schematics            8.3.21
@angular/cdk                                   8.2.3
@angular/cli                                      8.3.21
@angular/compiler-cli                      9.1.2
@angular/material                             8.2.3
@ngtools/webpack                           8.3.24
@schematics/angular                        8.3.21
@schematics/update                         0.803.21
rxjs                                                    6.4.0
typescript                                          3.5.3
webpack                                             4.39.2

"ngx-daterangepicker-material": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/ngx-daterangepicker-material/-/ngx-daterangepicker-material-3.0.1.tgz",
      "integrity": "sha512-4O3GWAYJaauMCILm07weko2rHA8a4kjn7+8Lg4s1d7SxwS/3IpkVD/GljbRrIJ1c1W/XGJ3GbuK7RyYZEJChhw=="
    },

i have done a downgrade to version 2.2 and the error it's still there

can't start project, throws ERROR in Cannot read property 'map' of undefined

**Comment by Timebutt** [comment]
I don't think this error is related to this package, rather the specific implementation of your app. The above doesn't give us much to go by either, can you show the line of code that's throwing this issue?

**Comment by edditrana** [comment]
the downgrade don't work. But it work when i clone my project again and install the 2.2 version from scratch. Thanks
