### ISSUE TITLE
Event are not emmiting

### ISSUE THREAD

**Issue by tlebreton** [fetrarij/ngx-daterangepicker-material#269]
Hi everybody

First thanks for this lib , i use the bootstrap daterangepicker for a long time and i switch to angular since a few month and this lib suits perfetcly.

After upgrading to 3.0.0 or 3.0.1 i notice that the event (datesUpdated and maybe other) are not emmited. You can reproduce it on the demo site on the custom range page.

Thanks for your work.

**Comment by Timebutt** [comment]
Hi @tlebreton, thanks for reporting this issue. Just looked into this, and there is in fact a regression that was introduced in 3+. 

https://github.com/fetrarij/ngx-daterangepicker-material/pull/271 fixes the issue ;)
