### ISSUE TITLE
ngx-datarange-picker-md not rendered inside component's template

### ISSUE THREAD

**Issue by yudarik** [fetrarij/ngx-daterangepicker-material#272]
After upgrading to the latest angular version 9.1 with ngx-daterangepicker-material@3.0.1
I've noticed that while used with ngxDaterangepickerMd derective attached to an input element, the ngx-dateragepicker-material component is no longer rendered inside of the parent component  as it was with version 2.2.X.
Instead it is rendered inside .cdk-overlay-container (direct child of the body element).
I understand that it's due to the angular material changes or angular 9.1 changes that have beed made....
The fact is that I'm using this model without a material theme, instead it's used with bootstrap 3.X,
so before the upgrade, I've used my own classes to style the module inside it's parent component.
Now, I need to fix the styling all over again..
Is there any way to render the module component inside an angular component, with the help of ngxDaterangepickerMd directive on this new version?

**Comment by fetrarij** [comment]
@yudarik hello, use v2.3.0

**Comment by yudarik** [comment]
Right, but that version does not supported under NG-9.
Anyway, I've found a workaround with the help of few extra css rules + and minimal material UI.

**Comment by fetrarij** [comment]
@yudarik 2.3.0 use angular v9 :)

**Comment by yudarik** [comment]
You're right... I didn't noticed that info on the home page:

>=9.0.0 | v2.3.x and v3.x
<9.0.0 | v2.2.x and below
