### ISSUE TITLE
Custom angular material theme

### ISSUE THREAD

**Issue by Rapiiidooo** [fetrarij/ngx-daterangepicker-material#273]
I have a custom angular material theme, everything is set up fine.

(This blue below is the one from my custom theme)

![image](https://user-images.githubusercontent.com/23468871/80500650-bbe55c00-896e-11ea-9f38-a030b42de2a9.png)

My problem is, I can actually see the submit button with my theme color, but why the selected range doesnt appear right (like the below example) ?

![image](https://user-images.githubusercontent.com/23468871/80500729-d28bb300-896e-11ea-837e-ac3d393425c7.png)

I don't want to override the class because I want to be able to change the theme during the session and then I don't want static class with static colors.
Do you have any clues about how to fix it ?

EDIT:

The material color for the submit button works from the version 3.0.0
But from this version I don't have at all the color either the background color for the selected days

**Comment by jgeiger-cr** [comment]
I just installed this with Angular 9 and v.3.0.1 and had the same issue until I realized they support themes in a first class way.  It all works perfectly.  In your styles.theme.scss (or wherever you import themes):

@import '../../node_modules/ngx-daterangepicker-material/daterangepicker-theme.scss';
@mixin oio-theme($theme) {
  @include date-range-picker-theme($theme);
}

**Comment by Rapiiidooo** [comment]
Thanks mate it works perfectly !

I actually found an other way but this one is much cleaner !

If you are interset it was to overload the background color and the color in function of light or dark

```
.theme {
    @include angular-material-theme($theme);
    .md-drppicker td.active, .md-drppicker td.available.in-range.active, button.active, .md-drppicker td.active:hover {
    background-color: map-get($theme, 'default') !important;
    color: white !important;
  }
}
```

**Comment by Rapiiidooo** [comment]
I reopen this issue for the latest release of the package

`@import '../../node_modules/ngx-daterangepicker-material/daterangepicker-theme.scss';` is not available anymore.

So how do we change the color with the custom theme ?

**Comment by blockerdude** [comment]
https://github.com/fetrarij/ngx-daterangepicker-material/issues/273#issuecomment-621362485

For those wondering this still works in version 3.0.4, but doesn't appear to be supported by any versions past that.

**Comment by Rapiiidooo** [comment]
As its been a long time, and not the prio, its maybe better to close this one for now.

Thanks to the dev team.

Feel free to reopen.
