### ISSUE TITLE
icon load

### ISSUE THREAD

**Issue by aylmercarson** [fetrarij/ngx-daterangepicker-material#276]
just a thought. i currently need to load the entire set of google material icons from https://fonts.googleapis.com/icon?family=Material+Icons' in order to just display the 2 back and forward arrows. i'm not sure if there are any other icon dependencies on the icon set. i prefer to have a curated set of icons which are application specific, implemented as svgicons, and so reduce the application size and startup time. i know that a lot of developers don't pay much attention to the icon dependency but it all helps. could you possibly indicate all icons required by this control so i could look at implementing this myself? thanks

**Comment by camillewall** [comment]
I agree. Even though I use angular material the icon set I prefer to use is font-awesome. It would be nice to not have to include all of materials icons for a left caret, right caret, and trash can.
