### ISSUE TITLE
Cannot see dashboard screen

### ISSUE THREAD

**Issue by sstc02** [fetrarij/ngx-daterangepicker-material#279]
ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[DaterangepickerDirective -> LocaleService]: 
  StaticInjectorError(Platform: core)[DaterangepickerDirective -> LocaleService]: 
    NullInjectorError: No provider for LocaleService!
NullInjectorError: StaticInjectorError(AppModule)[DaterangepickerDirective -> LocaleService]: 
  StaticInjectorError(Platform: core)[DaterangepickerDirective -> LocaleService]: 
    NullInjectorError: No provider for LocaleService!

**Comment by rayita** [comment]
Same problem here

**Comment by fetrarij** [comment]
Hello, which angular version and the component version do you use?

**Comment by rayita** [comment]
Already working here.
I'm using Angular 9 and tehere is waning in docs about the need to use the old '.forRoot()' initialization (instead the new 'providedIn').

I added initialization in the app.module and now is working fine.

Thanks

**Comment by fetrarij** [comment]
@sstc02 that's use .forRoot()
