### ISSUE TITLE
Latest v3.0.1 is not working with Angular 9

### ISSUE THREAD

**Issue by nickle72000** [fetrarij/ngx-daterangepicker-material#281]
Recently i updated my project from angular 8 to 9.  After that i am facing below issue
As soon as i click the input i am getting error ar "No component factory found for DaterangepickerComponent. Did you add it to @NgModule.entryComponents?"

**Comment by Yollty** [comment]
Had the same issue, even with the NgxDaterangepickerMd.forRoot()
It is working if I add the "entryComponents: [DaterangepickerComponent],"
But not sure why...
