### ISSUE TITLE
Drops and Opens are gone, whether it stands in a documentation (v.3.0.1)

### ISSUE THREAD

**Issue by devcomponent** [fetrarij/ngx-daterangepicker-material#287]
Hi,
please implement in version 3.0.1 again drops and opens. 
It was usefull for position it manually. Especially up and down. 
In some cases, the automatic position doesn't make a perfect match, what is excepted.
It is mentioned in the documentation and it was in 2.x but now is gone in 3.0.1 code

It is just in the daterangepicker.directive.d.ts but not in the daterangepicker.component.d.ts

Or is now an other way to position it manually?

Best Regards

**Comment by marsc** [comment]
We have the same problem. A fix would be good.

**Comment by devcomponent** [comment]
Thx fetrarij,
but you added the fix for the directive, not for the daterangepicker.component.ts as an Input.
I need this for the component. Cause we don't use it as a directive. We use it as a component.

**Comment by marsc** [comment]
As mentioned above this is still not working. A fix would be great.

**Comment by fetrarij** [comment]
@devcomponent if you use the component, it means it's for an inline so you wont use drops & opens at all.
v3.0.2 is up for the directive :)
