### ISSUE TITLE
How to hide the side ranges from the date range ?

### ISSUE THREAD

**Issue by kirandeep123** [fetrarij/ngx-daterangepicker-material#293]
[
<img width="549" alt="Screenshot 2020-06-16 at 1 35 48 PM" src="https://user-images.githubusercontent.com/31850870/84748522-61639600-afd6-11ea-9404-eced84d82433.png">
](url)

I want to display something like this?

**Comment by fetrarij** [comment]
@kirandeep123 hello,

like the example https://fetrarij.github.io/ngx-daterangepicker-material/reactive-forms
just dont provide the `ranges` attribute.
