### ISSUE TITLE
'emptyWeekRowClass' is not working in 2.1.10 version.

### ISSUE THREAD

**Issue by RtzS** [fetrarij/ngx-daterangepicker-material#294]
**Versions**
* Angular version: 7
* component version: 2.1.10

**Describe the bug**
- 'emptyWeekRowClass' is not working in 2.1.10 version.
- On click of clear button I don't want to close calendar. but calendar get closed. 

**Expected behavior**
'emptyWeekRowClass' is not working in 2.1.10 version. I don't want to show next month date in Current month.

**Screenshots**
![image](https://user-images.githubusercontent.com/8089250/84988156-1c1ea000-b15f-11ea-995a-03cef0a96941.png)

Thankyou in advance.
Any help will be appreciated.

**Comment by RtzS** [comment]
Hi All ,


I am still facing above mentioned issue. Can any one please help me to fix this.

Thankyou in adv :)

**Comment by fetrarij** [comment]
emptyWeekColumnClass is added for this.
v4.0.1 and v2.4.1 is up for this.
