### ISSUE TITLE
is there any possible way to select dates based on month selection?

### ISSUE THREAD

**Issue by akash-ngpws** [fetrarij/ngx-daterangepicker-material#298]
I'm working with your package and it's very reponsive and productive..please help me with these issue

![Screenshot (23)](https://user-images.githubusercontent.com/45391877/85741824-5e784c00-b720-11ea-9955-0f19c897dc52.png)
![Screenshot (24)](https://user-images.githubusercontent.com/45391877/85741836-60daa600-b720-11ea-9c85-0c1b057643c3.png)

Thanks in advance.

**Comment by fetrarij** [comment]
I think best way for your problem is to use the ranges like:

ranges = {
        'This Month': [moment().startOf('month'), moment().endOf('month')],
        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
        'Next Month': [moment().add(1, 'month').startOf('month'), moment().add(1, 'month').endOf('month')],
    };

Or create a month select and update the model with the selected
