### ISSUE TITLE
Support angular 10

### ISSUE THREAD

**Issue by Rapiiidooo** [fetrarij/ngx-daterangepicker-material#299]
**Versions**
* Angular version: 10
* component version:

**Describe the bug**
`Package "ngx-daterangepicker-material" has an incompatible peer dependency to "@angular/material" (requires "^9.0.0", would install "10.0.0").`

**To Reproduce**

`ng update @angular/cdk @angular/cli @angular/core @angular/material
`
**Expected behavior**
The update of ng update 😄 

Would be amazing guys 🥂

**Comment by fetrarij** [comment]
hello @Rapiiidooo could you check if the latest version (3.0.2) works with v10?

**Comment by Rapiiidooo** [comment]
Hello @fetrarij I confirm that everything is working correctly with the latest version (3.0.4) for angular v10

Thanks 👍

**Comment by fetrarij** [comment]
awesome @Rapiiidooo  thanks :)
