### ISSUE TITLE
show "2nd / to" calendar as per maxDate if provided

### ISSUE THREAD

**Issue by Ratikant01** [fetrarij/ngx-daterangepicker-material#3]
As, we have provided maxDate, there is no use of showing next month as 2nd calendar as those dates will not be selectable - instead, can it be maxDate's month as second calendar and prev month as first calendar?

![image](https://user-images.githubusercontent.com/5038421/40302407-a00e66e2-5d0c-11e8-8df4-c16b8ec9dc25.png)

**Comment by fetrarij** [comment]
It should be good from now.

Thank you.
