### ISSUE TITLE
Setting minDate and maxDate causing issues in month display

### ISSUE THREAD

**Issue by kavvya97** [fetrarij/ngx-daterangepicker-material#304]
angular version: 7
 "ngx-datepicker-material": "^1.0.1",

i made a simple project which just using the minDate and maxDate.

`<ngx-daterangepicker-material
[minDate]="minDate"
[maxDate]="maxDate"
[linkedCalendars]="true"
></ngx-daterangepicker-material>`

Now, in the sample demo provided
this was the min and max dates
` minDate: moment.Moment = moment().subtract(5, 'days');
    maxDate: moment.Moment = moment().add(2, 'month');`

Now this causes no issues. However, when i tweaked it like
`  minDate: moment.Moment = moment().subtract(2, 'months');
  maxDate: moment.Moment = moment();`

i see an issue where after may, july gets displayed

<img width="557" alt="Screenshot 2020-07-06 at 2 54 16 PM" src="https://user-images.githubusercontent.com/56823071/86578375-57133700-bf99-11ea-9754-040217a49f3c.png">

please help me on how to take forward this issue

**Comment by fetrarij** [comment]
Hello could you use v2.2.1 ?

**Comment by kavvya97** [comment]
works. thanks

**Comment by fetrarij** [comment]
@kavvya97 could you partipate in this https://github.com/fetrarij/ngx-daterangepicker-material/issues/308 ?

**Comment by Kushal-MP08** [comment]
@kavvya97  thanks works fine for me !!!!
