### ISSUE TITLE
Inline mode

### ISSUE THREAD

**Issue by fetrarij** [fetrarij/ngx-daterangepicker-material#31]
Add ability to set the calendar to inline.
With this options, it could be easy to set the calendar in a modal.
in this case we can track the apply event (may close the modal ...)

**Comment by fetrarij** [comment]
@butterknight Add ability to use directly the component: <ngx-daterangepicker-material></ngx-daterangepicker-material> That's what I did. 
For it, we need to add another state info (inline) so when called from directive it's should be forced to inactive, but by default (called without the directive) it's active :dagger:  
Then from this state we just add the required Css.
Can you test / add doc / improvments if found?

**Comment by butterknight** [comment]
I'll take a look at it as soon as I get a chance =)

**Comment by butterknight** [comment]
I've pushed an update #32 which handles a bug I found (described in the pull request). So far I haven't found any other issues.
