### ISSUE TITLE
"JNe.weekdaysMin is not a function" error after deployment.

### ISSUE THREAD

**Issue by VladPavliuk** [fetrarij/ngx-daterangepicker-material#314]
I get this error all the time after every deployment!

![Annotation 2020-07-20 143025](https://user-images.githubusercontent.com/24705251/87933262-9cedf600-ca95-11ea-8dea-df89ed04a2ae.png)

![Annotation 2020-07-20 143211](https://user-images.githubusercontent.com/24705251/87933387-d32b7580-ca95-11ea-983b-a03fec81830b.png)

"moment": "2.25.3"
"ngx-daterangepicker-material": "2.2.0"

Does anybody have an idea what's going on?

**Comment by fetrarij** [comment]
Hello :)
Could you share more information? angular version? the command for your deployment?

**Comment by VladPavliuk** [comment]
Hello
It's not relevant anymore. We've changed the approach we manage our modules.
I guess we can close this one.

**Comment by coolrb** [comment]
I now exactly have same problem when upgraded to Angular 9. I thought this is an issue with moment.js so raised an issue there https://github.com/moment/moment/issues
But I found this issue. What should I do now to resolve. Its almost an week since we last deployed our production. We are not contemplating to revert back to angular 8. But this is not the solution. Any help would really be appreciated.

**Comment by caohothang** [comment]
anyone have idea to fix it ?

**Comment by quimack** [comment]
I have the same problem @fetrarij 
https://github.com/fetrarij/ngx-daterangepicker-material/issues/478  --> Here more info

angular v10
ng build -c=development
gcloud app deploy -v 1

**Comment by quimack** [comment]
I can fix it changing the ngx-daterangepicker-material version!
in my case i have Angular10 and the compatible version is 4.x.x
 my package.json:
   "ngx-daterangepicker-material": "^4.0.1",
   "ngx-moment": "^5.0.0",

and uninstall dayjs. 
 

> I now exactly have same problem when upgraded to Angular 9. I thought this is an issue with moment.js so raised an issue there https://github.com/moment/moment/issues But I found this issue. What should I do now to resolve. Its almost an week since we last deployed our production. We are not contemplating to revert back to angular 8. But this is not the solution. Any help would really be appreciated.

**Comment by quimack** [comment]
pay attention to the versions
https://www.npmjs.com/package/ngx-daterangepicker-material

> anyone have idea to fix it ?
