### ISSUE TITLE
(Request to verify Feature) 'emptyWeekRowClass' is not working in 2.1.10 version.

### ISSUE THREAD

**Issue by RtzS** [fetrarij/ngx-daterangepicker-material#315]
Versions

Angular version: 7
component version: 2.1.10
Describe the bug

'emptyWeekRowClass' is not working in 2.1.10 version.
On click of clear button I don't want to close calendar. but calendar get closed.
Expected behavior
'emptyWeekRowClass' is not working in 2.1.10 version. I don't want to show next month date in Current month.

Screenshots
![image](https://user-images.githubusercontent.com/8089250/88255454-12480980-ccd6-11ea-9d06-8fe1ad9d39ee.png)

Thankyou in advance.
Any help will be appreciated

**Comment by RtzS** [comment]
Can any one please check this issue.

**Comment by fetrarij** [comment]
Hello. This is working well. However the class is added in the row section (tr) not the column one.
So the need you want may not emptyWeekRowClass.
Since I see this useful I am going to implement emptyWeekColumnClass.

**Comment by RtzS** [comment]
@fetrarij  Still issue is not resolved. 'emptyWeekColumnClass' is not working with V2.1.10.

**Comment by fetrarij** [comment]
@RtzS use v2.4.1

**Comment by RtzS** [comment]
@fetrarij Thankyou for quick reply after changing version v2.1.10 to v2.4.1  able to access 'emptyWeekColumnClass', bit still I am facing some issues in hiding date in week which are not part of current month. PFA
![image](https://user-images.githubusercontent.com/8089250/92243089-803f3d80-eede-11ea-8328-3b598c2fd574.png)


Here I want to show date of current month only but it is not working as expected. It looks like gap.
Can you please suggest any solution.

Thankyou in advance.
