### ISSUE TITLE
how to add class ngx-daterangepicker-action ?

### ISSUE THREAD

**Issue by armadillomx** [fetrarij/ngx-daterangepicker-material#317]
I've seen mention to add the class 'ngx-daterangepicker-action' to the element to open the picker, checked the sample code but I haven't found any reference on how the class is added

Added as follows doesn't work:

`<button mat-icon-button class="ngx-daterangepicker-action"  (click)="OpenDateRangePicker()" ><mat-icon>date_range</mat-icon></button>`

How to the class should be added?

Thanks

**Comment by fetrarij** [comment]
hi, which version?

**Comment by fetrarij** [comment]
@armadillomx and in your component call the open in the directive

`OpenDateRangePicker() { 
this.picker.open()
 }`
