### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by peturh** [fetrarij/ngx-daterangepicker-material#325]
**Versions**
* Angular version: ^10.0.12
* component version: ^3.0.4

**Describe the bug**
When including the datepicker there is only some styling applied. 

I've added the Datepicker module with: `import: [..., NgxDaterangepickerMd.forRoot(]),` and included the component with:

`<input type="text" ngxDaterangepickerMd [formControl]="filterForm.controls['date']" />`

It looks like this: 

https://imgur.com/sYHcPT0

The only CSS I've added is the Angular Material one:
`@import '../../node_modules/@angular/material/prebuilt-themes/purple-green.css';` in my styles.less

I've also added dependency @angular/material to the project.

There is CSS added to the page, this: https://pastebin.ubuntu.com/p/FwCV58d2bt/

When I go to the example page, I see that one has other CSS classes. When I copy pasted the CSS from the DOM on the Demo page and paste it in, everything looks as it should: https://imgur.com/M9Bli6r

CSS from demo page: https://pastebin.ubuntu.com/p/35Z4wkqGsp/

**To Reproduce**
Install packet through yarn and angular material. Include material theme in styles.less

**Expected behavior**
Expected to see correct datepicker CSS

It might be that I'm incredibly stupid, but I've searched and cant find anything.

**Comment by peturh** [comment]
Updated to `4.x.x` and styling started working.

**Comment by fetrarij** [comment]
hello,  v3 will not be maintained. thanks for using v4 of v2
