### ISSUE TITLE
Wrong README.md (4.x.x version does not exist on npm)

### ISSUE THREAD

**Issue by RupinSahu** [fetrarij/ngx-daterangepicker-material#326]
**Versions**
* Angular version: 10.0.9
* component version: 2.3.0

**Describe the bug**
I tried installing v4.0.0 version as it is provided in README.md but npm returned with error that it does not exist. So either update README.md or release v4 so that the confusion in installation can be removed

**To Reproduce**
1.  Type `npm i ngx-daterangepicker-material@^4.0.0` in terminal & press enter
2. See error - 
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for ngx-daterangepicker-material@4.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RupinPC\AppData\Roaming\npm-cache\_logs\2020-08-27T03_54_30_435Z-debug.log`

**Expected behavior**
On providing ^4.0.0 for version, it should install it

**Additional context**
Please refer to the README.md image
![image](https://user-images.githubusercontent.com/32542159/91387927-7f643700-e860-11ea-8b7e-db27260ba9d4.png)

**Comment by fetrarij** [comment]
Hello, thanks for reporting. I have just published the v4 and v2
