### ISSUE TITLE
Not possible to disable/enable input with FormControl disable/enable methods

### ISSUE THREAD

**Issue by manwithtwowatches** [fetrarij/ngx-daterangepicker-material#327]
If the ngxDaterangepickerMd input is part of FormGroup, the control's disable and enable methods have no effect on the input. It seems this behaviour is overridden somehow so that it always stays the same. The only way to disable the input is to include the raw disabled attribute in the HTML, but then it is not possible to enable the input after this. Setting the initial disabled config option of the FormControl at the time of initialisation also has no effect.

**Comment by fetrarij** [comment]
Fixed in this commit https://github.com/fetrarij/ngx-daterangepicker-material/commit/7c3265b64812684023ad290234d87f5ca443679e

**Comment by manwithtwowatches** [comment]
Thanks @fetrarij !

**Comment by manwithtwowatches** [comment]
@fetrarij I just tried this out with version 4.0.0 and it does not seem to be fixed. Behaves just the same as before.

**Comment by fetrarij** [comment]
v4.0.1 and v2.4.1 is up for this.

**Comment by manwithtwowatches** [comment]
Great stuff, thanks @fetrarij.
