### ISSUE TITLE
Opening calendar in 4.0.0 pops up within container.

### ISSUE THREAD

**Issue by dez1729** [fetrarij/ngx-daterangepicker-material#328]
![image](https://user-images.githubusercontent.com/20635596/91464656-a8c19a80-e841-11ea-8ad2-a43bcc0b5666.png)

Updating to 4.0.0 from 3.0.4 required me to remove the css link to angular material, but now when I opened the calendar the css merges into a container (in this case an angular material expansion panel).

**Comment by fetrarij** [comment]
@dez1729 Hello, v3 will not compatible with v4, dont upgrade, v4 is just a v2 but work with recent version of angular.
https://github.com/fetrarij/ngx-daterangepicker-material/issues/308
