### ISSUE TITLE
Could not resolve moment/ts3.1-typings/moment

### ISSUE THREAD

**Issue by rszemplinski** [fetrarij/ngx-daterangepicker-material#331]
**Versions**
* Angular version: 10.0.11
* component version: 4.0.1

**Describe the bug**
Every time I make a small change in the code and the code recompiles I get this error

```
Could not resolve moment/ts3.1-typings/moment from C:/Users/***/Documents/***/***/node_modules/ngx-daterangepicker-material/ngx-daterangepicker-material.d.ts
```

**To Reproduce**
1. Download package
2. Use component in code
3. Make any modification to the code while server is running

**Expected behavior**
No error

**Comment by Chmielinski** [comment]
Same on:
Angular v8.2.14
Component v2.4.1

**Comment by gopal-augment** [comment]
Same error in ng v9

Versions

    Angular version: 9.1.12
    component version: 4.0.1

**Comment by Chmielinski** [comment]
Looks like downgrading moment to v2.24.0 solved the issue.

**Comment by gopal-augment** [comment]
@Chmielinski Yeah, one thing need to confirm this moment version have to install from our project root directory package.json,  right?

**Comment by Chmielinski** [comment]
@gopal-augment That's right. Just remove your node_modules directory and run npm install or yarn install and you should be good to go.

**Comment by gopal-augment** [comment]
Thank You

**Comment by rszemplinski** [comment]
@Chmielinski so this did not work for me. I just had to revert back to moment 2.24.0 and it's working now.
