### ISSUE TITLE
ERROR in Could not resolve moment/ts3.1-typings/moment 

### ISSUE THREAD

**Issue by prachigupta2607** [fetrarij/ngx-daterangepicker-material#336]
**Versions**
* Angular version:  9.1.8
* component version: 4.0.1
* moment: 2.28
* tslib: ^1.10.0

**Describe the bug*:
Getting ERROR in Could not resolve moment/ts3.1-typings/moment  from ..../angular/node_modules/ngx-daterangepicker-material/ngx-daterangepicker-material.d.ts when angular code re-compiles for changes.

Please help me out.

**Comment by muhitoLV** [comment]
Same issue

**Versions**

- Angular version: 10.0.6
- Component version: 4.0.1
- moment: 2.28.0
- tslib: 2.0.0

On compile throws error:
ERROR in Could not resolve moment/ts3.1-typings/moment from .../node_modules/ngx-daterangepicker-material/ngx-daterangepicker-material.d.ts

**Comment by fetrarij** [comment]
@muhitoLV @prachigupta2607 try to downgrade your moment, use 2.27.0 instead.

**Comment by prachigupta2607** [comment]
> @muhitoLV @prachigupta2607 try to downgrade your moment, use 2.27.0 instead.
It didn't work. Still getting the same issue.

**Comment by fetrarij** [comment]
I have tried with this config 

* Angular version: 10.0.6
* Component version: 4.0.1
* moment: 2.28.0
* tslib: 2.0.0

and works like a charm.

**Comment by manalikatkar02** [comment]
Getting ERROR in Could not resolve moment/ts3.1-typings/moment from ..../angular/node_modules/ngx-daterangepicker-material/ngx-daterangepicker-material.d.ts when angular code re-compiles for changes.

After that i have only installed moment with below command:
      npm i moment
and its worked for me.

**Comment by dmrugalski** [comment]
My solution was comment out those lines in:
```
//  "angularCompilerOptions": {
//    "enableIvy": false
//  }
```
and add this line into compilerOptions: 
```
"allowSyntheticDefaultImports": true,
```

**Comment by tmgayathri** [comment]
I am getting the same error after Angular 9 upgrade. I'm using the below components:
Angular: 9.1.13
Moment: 2.29.1
ngx-daterange-picker: 2.4.1
tslib: 1.10.0

Also I have the enableIvy: false as its needed for my upgrade

I tried most of the above solutions:
1. Downgrade moment to 2.27.0, 2.24.0
2. using component version 4.0.1
3. Using the exact component version (without the "^")

Any suggestion would be helpful.

**Comment by Nasruddinkhan** [comment]
Getting ERROR in Could not resolve moment/ts3.1-typings/moment 
I tried most of the above solutions:

**Comment by fetrarij** [comment]
Hello, moment is replaced by dayjs in this component.
Use the latest version.

Thanks
