### ISSUE TITLE
Setting the "locale" attribute to anything results in manually editing the date in the input not working

### ISSUE THREAD

**Issue by manwithtwowatches** [fetrarij/ngx-daterangepicker-material#340]
4.0.1
Angular 2+

Setting the locale to any value (that I have tried) results in not being able to manually change the date/time by editing the text input. The date usually instantly changes to something a few years in the past before anything has even changed, and any changes you make are never reflected in the open date picker. Sometimes it results in a processor leak which results in the hanging/crashing of the browser.

1. This is even reproducable in the "Full options" demo 

If you don't set the locale attribute then it works fine as expected.

**Comment by dzena** [comment]
`format` and `displayFormat` of the `locale: LocaleConfig` object need to have the same format.
`this.pickerLocale = {
      customRangeLabel: this._translationService.translate(
        'DateTimePicker.customRange'
      ),
      applyLabel: this._translationService.translate('apply'),
      format: moment.localeData(this.locale.dateLanguage).longDateFormat('L'),
      displayFormat: moment
        .localeData(this.locale.dateLanguage)
        .longDateFormat('L'),
      daysOfWeek: moment.weekdaysMin(),
      monthNames: moment.monthsShort(),
      firstDay: moment.localeData(this.locale.dateLanguage).firstDayOfWeek(),
    };`

In the "Full options" demo, only the `format` is changed, that is the reason for the "bug".

**Comment by manwithtwowatches** [comment]
Well if it doesn't function properly when they have different values, then there is no need to have 2 different options as they always have to be the same. So at the least then one of the options should be removed to avoid confusion. Either that or is is a bug.

**Comment by manwithtwowatches** [comment]
But thanks for your reply @dzena, it's working now.
