### ISSUE TITLE
Template parse errors: 'ngx-daterangepicker-material' is not a known element: when using as inline element

### ISSUE THREAD

**Issue by dwjohnston** [fetrarij/ngx-daterangepicker-material#35]
I have added `NgxDaterangepickerMd` to my `@NgModule` imports, and using the non-inline mode works fine. 

eg. 

```
    <input ngxDaterangepickerMd [(ngModel)]="selected"  matInput placeholder="Date" [(ngModel)]="value">
```

However - using it as an inline component doesn't seem to be working properly: 
```  
<ngx-daterangepicker-material (choosedDate)="choseDate($event)">
  </ngx-daterangepicker-material>
```

```
compiler.js:215 Uncaught Error: Template parse errors:
'ngx-daterangepicker-material' is not a known element:
1. If 'ngx-daterangepicker-material' is an Angular component, then verify that it is part of this module.
2. If 'ngx-daterangepicker-material' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  </section>

  [ERROR ->]<ngx-daterangepicker-material (choosedDate)="choseDate($event)">
  </ngx-daterangepicker-material>
```

**Comment by fehtrar** [comment]
Hello, do you use the latest version?

**Comment by fetrarij** [comment]
Will take a look on this soon

**Comment by fetrarij** [comment]
Which version do you use?

**Comment by dwjohnston** [comment]
I'm using `1.2.0` according to the package.json. 

I reproduced it in a fresh angular install here; 

https://github.com/dwjohnston/ngx-daterangepicker-bug

You should be able to clone, install and run and see it.

**Comment by dwjohnston** [comment]
Any idea when this fix will be published?

**Comment by fetrarij** [comment]
I thought I could fix all issues for a new release but since you're pressed I've just released a new version (1.2.1).

**Comment by dwjohnston** [comment]
Thanks heaps :) :heart: :kissing_heart:

**Comment by mayanksaraswat04** [comment]
Getting the same issue with angular 9. what is the fix for this?
