### ISSUE TITLE
Allow blocking a range of list of dates. 

### ISSUE THREAD

**Issue by dwjohnston** [fetrarij/ngx-daterangepicker-material#36]
I want to use this date picker for a scheduling app. 

The minDate and maxDate is step towards what I want to use it for - what I would like to do is supply it with a list of dates that are already taken, and have those be blocked out. 

Is this feature already available or is it in the works?

**Comment by dwjohnston** [comment]
Ok, easy, I see it can be done with the `isInvalidDate` function. 

I will submit a pull request to update your documentation.

**Comment by dwjohnston** [comment]
PR here: https://github.com/fetrarij/ngx-daterangepicker-material/pull/37

**Comment by fetrarij** [comment]
Will check the PR :) thanks

**Comment by fetrarij** [comment]
on README, just use `isInvalidDate` function.
