### ISSUE TITLE
Question: Is it possible to show one calendar with range picker?

### ISSUE THREAD

**Issue by qwe12e** [fetrarij/ngx-daterangepicker-material#362]
singleDatePicker option shows one calendar but we can't use range.

**Comment by telmaco** [comment]
I am looking for this as well. ❤

**Comment by tarasmatsyuk** [comment]
I just hid right calendar
`.calendar.right {
  display: none !important;
}`

**Comment by qwe12e** [comment]
> I just hid right calendar
> `.calendar.right { display: none !important; }`

yeah that came to my mind too but how are you gonna click the next month button?

**Comment by tarasmatsyuk** [comment]
@qwe12e hmmm good point )
 but for my needs, 1 calendar is enough

**Comment by tarasmatsyuk** [comment]
@qwe12e but it works the same for 1 calendar 
![image](https://user-images.githubusercontent.com/12542304/111365295-ffd27400-869a-11eb-98fa-d64be019f925.png)
![image](https://user-images.githubusercontent.com/12542304/111365352-1082ea00-869b-11eb-81dd-073f40d3daeb.png)

**Comment by qwe12e** [comment]
@tarasmatsyuk can you share your code? i guess the problem is my configs.

**Comment by tarasmatsyuk** [comment]
@qwe12e 
`<ngx-daterangepicker-material (choosedDate)="selectDate($event)"
                              [alwaysShowCalendars]="true"
                              #datePicker
                              [autoApply]="true">
</ngx-daterangepicker-material>`

**Comment by qwe12e** [comment]
okey i found the problem. `linkedCalendars` property causes this problem. Everything works if I give a `false` value on mobile. Thank you @tarasmatsyuk.
