### ISSUE TITLE
Don't close the calendar after choosing a range

### ISSUE THREAD

**Issue by richbighouse** [fetrarij/ngx-daterangepicker-material#38]
Allow keeping the calendar open after selecting a range. 

For example, after clicking "Last 7 Days", I'd like the see the following:

![image](https://user-images.githubusercontent.com/8991138/44425543-2b7c3480-a55a-11e8-8836-da4c64a1f666.png)

**Comment by fetrarij** [comment]
Adding an option maybe. Will take a look on it soon, I am on holidays.
