### ISSUE TITLE
Select month or year not work

### ISSUE THREAD

**Issue by dongloc94** [fetrarij/ngx-daterangepicker-material#381]
**Versions**
* Angular version: 12
* component version: v5.0.0

**Describe the bug**
When I use the showdropdowns flag is true, clicking select the month or day it doesn't change the bottom calendar box

**Comment by bendzinks** [comment]
Hello. `monthOrYearChanged` must be changed like this
`if (isLeft) {
        this.leftCalendar.month = this.leftCalendar.month.month(month).year(year);
        if (this.linkedCalendars) {
            this.rightCalendar.month = this.leftCalendar.month.add(1, 'month');
        }
    }
    else {
        this.rightCalendar.month = this.rightCalendar.month.month(month).year(year);
        if (this.linkedCalendars) {
            this.leftCalendar.month = this.rightCalendar.month.subtract(1, 'month');
        }
    }`

**Comment by michaelferwer** [comment]
I have open a PR for that : https://github.com/fetrarij/ngx-daterangepicker-material/pull/383

**Comment by fetrarij** [comment]
Hello, sorry for the late response. I have just merged it and will release.
