### ISSUE TITLE
Ng build with --aot and --prod generates error - qu.weekdaysMin is not a function (Angular 9)

### ISSUE THREAD

**Issue by coolrb** [fetrarij/ngx-daterangepicker-material#384]
Describe the bug
We recently upgraded angular to verion 9.
Angular CLI: 9.1.15
Node: 12.22.1
OS: darwin x64
Angular: 9.1.13
The moment js version is 2.29.1
After deploying the app, we are getting error
`Uncaught TypeError: qu.weekdaysMin is not a function`
But this is not generated in dev environment. Only in minimized prod environment, it gives error. We are struggling from last 2 days.
The problem occurs in minified version only.
```
const qu = ju,
    Vu = new l.InjectionToken('daterangepicker.config'),
    Uu = {
      direction: 'ltr',
      separator: ' - ',
      weekLabel: 'W',
      applyLabel: 'Apply',
      cancelLabel: 'Cancel',
      clearLabel: 'Clear',
      customRangeLabel: 'Custom range',
      daysOfWeek: qu.weekdaysMin(),
      monthNames: qu.monthsShort(),
      firstDay: qu.localeData().firstDayOfWeek()
    };
```

**Comment by apangr** [comment]
it happens the same to me. Help!

**Comment by coolrb** [comment]
Downgraded to 
`"ngx-daterangepicker-material": "^4.0.1",`
That solved the problem. The environment
```
Angular CLI: 9.1.15
Node: 12.22.1
OS: darwin x64
Angular: 9.1.13
```
