### ISSUE TITLE
Next month calendar doesn't show up if the preview dates for next month covers the range.

### ISSUE THREAD

**Issue by praveenpuglia** [fetrarij/ngx-daterangepicker-material#40]
I know the title is confusing so here's a picture to go along with it.

![image](https://user-images.githubusercontent.com/313363/44981156-65542e80-af8f-11e8-9757-8e54647d3ac9.png)

I selected **THIS MONTH** and that range falls under the preview dates or advance dates that the August calendar shows for the September month. 

In this case, the calendar doesn't show the September month at all. Even clicking on that right arrow doesn't take me to September calendar.

**Comment by fetrarij** [comment]
Hello, I tried to reproduce but without success, could you try to reproduce it by forking the stackblitz link: https://stackblitz.com/edit/ngx-daterangepicker-material-uwpplc

**Comment by praveenpuglia** [comment]
https://stackblitz.com/edit/ngx-daterangepicker-material-yarguz?file=src%2Fapp%2Fapp.component.html

Happens when the `maxDate` is set to `moment()`

**Comment by praveenpuglia** [comment]
Thanks @fetrarij :)

**Comment by praveenpuglia** [comment]
When are you going to publish the fix if I may ask?

**Comment by fetrarij** [comment]
I've just released the v1.2.1. Thanks for reporting
