### ISSUE TITLE
TypeError when setting showWeekNumbers = true

### ISSUE THREAD

**Issue by manwithtwowatches** [fetrarij/ngx-daterangepicker-material#401]
* Angular version: 11.0.5
* component version: 5.0.1

**Describe the bug**
When setting the week numbers flag I get the following error

```
TypeError: ctx_r33.calendarVariables.left.calendar[row_r32][0].week is not a function
    at DaterangepickerComponent_div_5_table_2_tr_15_td_1_Template (ngx-daterangepicker-material.js:153)
```

**To Reproduce**
Make an angular project and use the code copy pasted from the examples page. Any picker with showWeekNumbers = true seems to result in this.

**Comment by fetrarij** [comment]
@manwithtwowatches Hi, I guess this is solved by your PR? Thank you very much :)

**Comment by arsolvit** [comment]
Hi @fetrarij! Will this PR be released in npm soon? This issue is so critical for us. Thanks!
