### ISSUE TITLE
Please publish the package with Ivy Distribution

### ISSUE THREAD

**Issue by jmtt89** [fetrarij/ngx-daterangepicker-material#418]
**Versions**
* Angular version: 13.2.0
* component version: 5.0.1

**Describe the bug**
After upgrade to Angular 13, Ivy distribution is norm, and View Engine is now legacy. 
When built it shows a message 

```shell
Processing legacy "View Engine" libraries:
- ngx-daterangepicker-material [fesm2015/esm2015] (https://github.com/fetrarij/ngx-daterangepicker-material.git)
- ngx-daterangepicker-material [esm2015/esm2015] (https://github.com/fetrarij/ngx-daterangepicker-material.git)
- ngx-daterangepicker-material [main/umd] (https://github.com/fetrarij/ngx-daterangepicker-material.git)
...
Encourage the library authors to publish an Ivy distribution.
```

**To Reproduce**
Build any Angular v13 Project with ngx-daterangepicker-material

**Comment by technbuzz** [comment]
Yeah, this is so annoying

**Comment by krechtern** [comment]
We also want to update to angular 13 and have these library as dependency. Would be cool if a new version would be published.
