### ISSUE TITLE
Showing the preset label doesn't work for the first time with supplied date.

### ISSUE THREAD

**Issue by praveenpuglia** [fetrarij/ngx-daterangepicker-material#45]
![image](https://user-images.githubusercontent.com/313363/45406623-b1d0f580-b684-11e8-83b1-fa055f4b314f.png)

I have provided here the start and end dates using `[(ngModel)]`. Once I click on the preset and click on apply, then on it starts showing the label. Not before that.

P.S - Do you also have some donation link? You have done a lot for us and me personally.

**Comment by fetrarij** [comment]
Thank you for reporting. 
I have added a donation button in readme.

**Comment by praveenpuglia** [comment]
Hey! Donated something! `4NN411905Y185710D` is the related ID. Let me know if you received it :)
