### ISSUE TITLE
isInvalidDate still allow for selecting a range on either side of the invalid date. 

### ISSUE THREAD

**Issue by dwjohnston** [fetrarij/ngx-daterangepicker-material#46]
This is perhaps a tricky issue as, perhaps you want to allow people to do that (ie. blocking out weekends, but allowing people to still select that range). 

In which case - the user could apply their own 'unselect the range' function with `datesUpdated` - but for the inline picker this means you need to be able to set the set the start date and end date as inputs.

**Comment by fetrarij** [comment]
Hello, I tried to understand but I couldnt. Could you give more details on this?

**Comment by dwjohnston** [comment]
Sure, so say you have January 20 and 21 disabled,  you can still select a the range 18th Jan to 23rd Jan .

**Comment by fetrarij** [comment]
Thanks,
What would be the right behaviour when this happened in your opinion?
A result with an array of all available date? or the first available date? or just not return a result?

**Comment by dwjohnston** [comment]
I think there should be two options.

The first is that it returns a list of dates within the range, excluding
the invalid dates.

The second is that it's an invalid selection.

**Comment by fetrarij** [comment]
@dwjohnston  if there are InvalidDates from isInvalidDate function, range (with a date invalid) becomes the first range until the first invalid date.
Does this statement solve this issue?

**Comment by fetrarij** [comment]
https://github.com/fetrarij/ngx-daterangepicker-material/commit/14488fb2fc336120ba407944d9176301e162d31e this is the commit.

**Comment by fetrarij** [comment]
v1.2.5 is up for it.

**Comment by marshall86** [comment]
> @dwjohnston if there are InvalidDates from isInvalidDate function, range (with a date invalid) becomes the first range until the first invalid date.
> 
> For our example (say you have January 20 and 21 disabled, you can still select the range 18th Jan to 23rd Jan .), the range become: 18th Jan to 19 Jan (since 20 is the first disabled)
> 
> Does this statement solve this issue?


About this issue, if i select a range of dates and there are some disabled in said range, the result should be the full range in any case with the disabled dates showed in the calendar.

Can you fix it please?
