### ISSUE TITLE
show only first and last selected months in calendar

### ISSUE THREAD

**Issue by lzhang0** [fetrarij/ngx-daterangepicker-material#464]
Is there an option to show only first and last selected month in the calendar when we select a larger range of days?

For example, I have selected the last 90 days from the range selection, I want to see May on the left calendar and August on the right calendar not May and June the consecutive months. 

Have tried [linkedCalendars]="false" and that will only show what I'm expecting when I click apply and reopen the picker.

**Comment by fetrarij** [comment]
hello @lzhang0 which version of the component do you use? agular version?

**Comment by lzhang0** [comment]
@fetrarij thanks for resolving this so quickly! We are using angular 11, will the fix be available for v5.x.x?
