### ISSUE TITLE
(rangeClicked) doesn't fire when we click Okay or apply button

### ISSUE THREAD

**Issue by umfaruki** [fetrarij/ngx-daterangepicker-material#48]
(rangeClicked) doesn't fire when we click Okay or apply button in custom range calendar view. If this behavior is correct than how can I attach event on APPLY button.

**Comment by umfaruki** [comment]
I tried this as well (choosedDate). but it never get fired

**Comment by fetrarij** [comment]
Hello, sorry for late reply.

> (rangeClicked) Fired when clicked on range, and send an object with range label and dates value, eg: {label: 'This Month', dates: [Moment, Moment]}  

So it's fired when you click on "Today" or "Yesterday" ... all you defined in your the `ranges` attributes

> (datesUpdated)
> Fires when  the date model is updated, like applying (if you have the activated the apply button),  or when selecting a range or date without the apply button or cancelling changes, and sends an object containing start and end dates, eg: {startDate: Moment, endDate: Moment}

This should only fired when date is updated. I'm adding some change to have this behaviour

**Comment by fetrarij** [comment]
So if you want to track for apply button, you can use (datesUpdated), but the (rangeClicked) is for clicking a range (eg: click on Yesterday, This month,...)
