### ISSUE TITLE
Allow it to be used on select elements as well as input

### ISSUE THREAD

**Issue by Hamaze** [fetrarij/ngx-daterangepicker-material#49]
It'd be great if this could be similiar to the bootstrap version on select elements as well as inputs.

**Comment by fetrarij** [comment]
Hello, could you point me where in the bootstrap version has this behaviour?
I saw one with a div..

**Comment by Hamaze** [comment]
I'm not exactly sure how it's doing it on a mat-select component but the ng2-daterangepicker which is bootstrap based is able to work against a mat-select and I think that is in fact because it binds to a div as opposed to an input element specifically. Again I'm not really sure though.

**Comment by fetrarij** [comment]
It's not on select element. It's still an input element but with custom ranges  and set alwaysShowCalendar to false, something like:

```html
<input type="text"
  ngxDaterangepickerMd
  [(ngModel)]="selected"
  [alwaysShowCalendars]="false"
  [ranges]="ranges">
```

and 

```typescript
ranges: any = {
    'Today': [moment(), moment()],
    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
    'This Month': [moment().startOf('month'), moment().endOf('month')],
    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
  }
```
