### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by jerone** [fetrarij/ngx-daterangepicker-material#491]
Will this package support Angular 15.

**Comment by jerone** [comment]
@fetrarij 🏓

**Comment by jerone** [comment]
@fetrarij 
Do you have any plans to update this package?
If the answer is "no" or "not in the near future", that's fine, then my team can search for alternatives.

**Comment by fetrarij** [comment]
Hello @jerone , I need to have time for that.
If you are  in hurry, don't hesitate to work on it and create a PR .

Thanks

**Comment by jerone** [comment]
Sorry my message sounded like pushing. My intention was only to know the planning. No rush.

**Comment by mayurrawte** [comment]
@jerone tried implementing similar https://www.npmjs.com/package/ngx-mdc-daterange-picker in angular 15
