### ISSUE TITLE
I've got an issue while selecting year 1972, why dind't you allow searching backwards from 1972 

### ISSUE THREAD

**Issue by congminh69** [fetrarij/ngx-daterangepicker-material#499]
Angular version: 13.3.1
![image](https://user-images.githubusercontent.com/38394287/207298533-f5ab8999-0f35-4c15-ab55-6b022322e9ac.png)
![image](https://user-images.githubusercontent.com/38394287/207298490-d3e09cdd-c1cd-4af5-8f5f-0574e588e976.png)

**Comment by sai-gmbh** [comment]
I am still having the same issue. Can you tell me how you fixed this issue?
