### ISSUE TITLE
setPosition

### ISSUE THREAD

**Issue by jordibaliellas** [fetrarij/ngx-daterangepicker-material#50]
In some cases the datepicker is not well placed, I have seen that you have the function setPosition, how do I trigger that function? Thank you

**Comment by luguiant** [comment]
Hi, how did you solve it? I have just the same problem.

**Comment by jordibaliellas** [comment]
I don't remember it all right. but I think if you put the id and from the ts instances a viewChild with the id of the datarangepicker from the ts you can call the function setPosition()

**Comment by luguiant** [comment]
I already found a solution to this issue, using angular overlay, look at this post where I give a solution, at the moment it seems to me an acceptable solution

https://github.com/fetrarij/ngx-daterangepicker-material/issues/198
