### ISSUE TITLE
Month order issue

### ISSUE THREAD

**Issue by balwant-singh1707** [fetrarij/ngx-daterangepicker-material#51]
Hi,

there is an issue with the daterangepicker that when a user goes one month forward and then comes back to original month, the order of month changes.

Example :  https://fetrarij.github.io/ngx-daterangepicker-material/full

open the calender from dropdown, now move to next month using the arrow ( > ) on top right corner i.e Dec 2018- Jan 2019, now move back using ( < ) arrow on top left corner, the month now will change to Oct 2018-Dec 2018, instead of Nov 2018- Dec 2018

**Comment by fetrarij** [comment]
Hello,
Could you retry? I dont have that issue from this link: https://fetrarij.github.io/ngx-daterangepicker-material/full

**Comment by fetrarij** [comment]
Since we dont have new from you @balwant-singh1707 I'm closing the issue now.
Feel free to reopen if needed.

Thanks
