### ISSUE TITLE
Selecting any date without range throws an Error in console and broke the functionality.

### ISSUE THREAD

**Issue by sunrawat** [fetrarij/ngx-daterangepicker-material#514]
**Versions**
* Angular version: v6.x.x
* component version: v6.x.x

**Describe the bug**
Selecting any date without range throws an Error in console Cannot read properties of undefined (reading 'selectedHour').
I was also able to reproduce the issue in official website also and all the Web application using this plugin or module.
Whether in Jquery, Javascript or Angular applications.

**To Reproduce**
1. Go to https://fetrarij.github.io/ngx-daterangepicker-material/custom-ranges
2. Click on date field
3. Click on any date once only and click Done
4. Open the console and see the error 

**Expected behavior**
Current selected start date(02/022/2023) should be selected for example
02/022/2023 - 02/022/2023
I should have take start date as the end date on (one selection) instead throwing error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3772204/220833732-44972f7c-1067-426e-a668-d7db17fe8413.png)

**Stackblitz link**
https://fetrarij.github.io/ngx-daterangepicker-material/custom-ranges

**Additional context**
Issue is coming from there in the code:

 function which is causing issue: **timepickerVariables**

clickApply(e) {
        if (!this.singleDatePicker && this.startDate && !this.endDate) {
            this.endDate = this.getDateWithTime(this.startDate, SideEnum.right);
            this.calculateChosenLabel();
        }
}

getDateWithTime(date, side) {
        let hour = parseInt(String(this.timepickerVariables[side].selectedHour), 10);  <<<< **source of error** 

Hope we'll get an update soon.

**Comment by sunrawat** [comment]
@fetrarij Do you have any updates on this?

**Comment by hannata** [comment]
any updates ?

**Comment by Sky4CE** [comment]
If you have global error handler implemented in your project then it is not possible to suppress this error. @fetrarij please give your thoughts about this

**Comment by hannata** [comment]
so we downgrade and keep on using the old version for now ?

**Comment by sunrawat** [comment]
Shall we proceed with the Pull Request Raised and merge it? @hannata @Sky4CE @fetrarij

**Comment by hannata** [comment]
gents, im gonna downgrade now, until it has a stable version that can fix this issue and ill upgrade, as i can handle warnings, but the error breaks the app

**Comment by Sky4CE** [comment]
@hannata the only way suppress it is too add special case in global error handler and match against exact text, but this is too ugly. By the way what version did you downgrade to avoid this error ?

**Comment by hannata** [comment]
> @hannata the only way suppress it is too add special case in global error handler and match against exact text, but this is too ugly. By the way what version did you downgrade to avoid this error ?

to version ^5.0.2 @Sky4CE

**Comment by Sky4CE** [comment]
Hi @fetrarij , could you inform please when you plan to release this fix to npm ?

**Comment by hannata** [comment]
hello everyone, i want to upgrade to angular 17, so first im upgrading to angular 16, but i was getting an erro from the daterange package, i has to upgrade it too, so now im back with the selectedHour issue, any update on this ? and how can we solve it ?

**Comment by hannata** [comment]
any updates ?
