### ISSUE TITLE
Setting the timePicker to true doesn't show the select boxes to choose times

### ISSUE THREAD

**Issue by daanvanrobays** [fetrarij/ngx-daterangepicker-material#52]
Hey there

First of all, great Daterangepicker component! I've been looking out for one that uses material design.

But setting the timePicker boolean to true doesn't doesn't show the select boxes to choose times in addition to dates.

Perhaps there is something I missed? I am using the code below to achieve my goal.

```
<mat-form-field>
     <span matPrefix class="fa fa-calendar"></span>
     <input type="text" matInput ngxDaterangepickerMd [locale]="{format:'DD/MM/YYYY HH:mm',firstDay:1}" />
</mat-form-field>
```

```
@ViewChild(DaterangepickerDirective) daterangeDirective: DaterangepickerDirective
this.daterangeDirective.picker.timePicker = true;
```

**Comment by ydcode** [comment]
TimePicker Feature +1

Great Job ,   thanks man~~

**Comment by fetrarij** [comment]
it's added with v1.2.6.
Thanks
