### ISSUE TITLE
 Positioning of the calendar using drop property

### ISSUE THREAD

**Issue by PatriceMoreau56** [fetrarij/ngx-daterangepicker-material#54]
When i'm using the drop property "up" on an input to toggle the drop menu, the menu doesn"t systematically open on the desired place. I'm using Angular 6.0.0.

You can try this on your own example, using property center/top.
Any idea how to solve this?

Thks

**Comment by fetrarij** [comment]
@PatriceMoreau56  how's your code? do you use drops or drop? should be `drops="up"`

**Comment by fetrarij** [comment]
Since there are no response from you, I consider it that you were using drop instead of drops.
I'm closing the issue now, feel free to reopen if needed.

**Comment by AvinashPatil9850** [comment]
I also have same problem 

`<input class="btn btndate" style="background-color:lightgray"
               ngxDaterangepickerMd
               placeholder="Select"
               [locale]="{applyLabel: 'Apply', format: 'DD-MMM'}"
               [showCustomRangeLabel]="true"
               [alwaysShowCalendars]="false"
               [opens]="right"
               [ranges]="ranges"
               [drops]="up"
               [linkedCalendars]="true"
               [isInvalidDate]="isInvalidDate"
               [showClearButton]="true"
               [(ngModel)]="selected"
               [showRangeLabelOnInput]="false" />
![daterangepicker](https://user-images.githubusercontent.com/46689416/70026523-1055fc80-15c6-11ea-8264-84815d656ccb.png)
`
this is my code not working properly
dropdown going to out of view

**Comment by AvinashPatil9850** [comment]
> Since there are no response from you, I consider it that you were using drop instead of drops.
> I'm closing the issue now, feel free to reopen if needed.

hello fettrarij can you help me solve this issue please

**Comment by Srisylam** [comment]
could you please write below like this
 [drops]="'down'"
         [opens]="'right'"
