### ISSUE TITLE
startDate and endDate inverted for custom range picker

### ISSUE THREAD

**Issue by bnoeson** [fetrarij/ngx-daterangepicker-material#6]
Hi!

thanks for this nice component! Since angular material isn't implementing a date range picker, your component is very useful.

I have noticed a bug, reproducible with your demo page : 

![issue-start-and-end-date](https://user-images.githubusercontent.com/23740164/40889064-78023b66-6760-11e8-8727-fc1fb4308a8d.JPG)

startDate and endDate are inverted. The endDate is before the startDate.

Could you look at it?

**Comment by fetrarij** [comment]
Hello @bnoeson ,

Thank you for reporting the issue.

**Comment by fetrarij** [comment]
Thank you.

v1.0.6 is up, and the running demo https://fetrarij.github.io/ngx-daterangepicker-material/custom-ranges

**Comment by bnoeson** [comment]
ok, thanks for the fix!
