### ISSUE TITLE
Difficult to modify CSS

### ISSUE THREAD

**Issue by daniel-fuelx** [fetrarij/ngx-daterangepicker-material#60]
It's difficult for me to modify this lib's CSS. Now what I can do only is using !important & ::ng-deep.  
Using ::ng-deep alone cannot work.  

I recommend writing CSS in ng-select way. see https://github.com/ng-select/ng-select/blob/f84906b550284968e9cc9715c60c8dcde92a3780/src/ng-select/ng-select.component.ts#L67  

Any plan on this? Thx.

**Comment by finley-fuelx** [comment]
some issue +1
