### ISSUE TITLE
 .btn / .buttons / .clear classes may pollute other libraries..

### ISSUE THREAD

**Issue by daniel-fuelx** [fetrarij/ngx-daterangepicker-material#62]
https://github.com/fetrarij/ngx-daterangepicker-material/blob/2e649c6a875e856502c8f44744978b47ec4dd573/src/daterangepicker/daterangepicker.component.scss#L633

related to https://github.com/fetrarij/ngx-daterangepicker-material/issues/60
After exposed CSS to global, these .btn / .buttons / .clear classes may pollute other libraries.  
How about moving all these css under .md-drppicker ?  

What's your plan ? 
Or using ShadowDom instead of None ?
thx.

**Comment by fetrarij** [comment]
Hi, thanks for the report @daniel-fuelx .
What's the best suits for this? personally I thought about changing classes...
