### ISSUE TITLE
Default Date Range For Inline Mode

### ISSUE THREAD

**Issue by jsanjeev** [fetrarij/ngx-daterangepicker-material#64]
Hi, Is it possible to pass default date range for date picker in inline mode , unable to use **ngModel**  in date range picker while using inline mode

**Comment by daanvanrobays** [comment]
Hi @jsanjeev 

I achieved setting a default date range programmatically the following way:

```
@ViewChild(DaterangepickerComponent) datePicker: DaterangepickerComponent;

this.datePicker.setStartDate(yourStartDate);
this.datePicker.setEndDate(yourEndDate);
this.datePicker.updateCalendars();
```

Although the timepicker seems to be left out for some reason I haven't figured out yet.

I hope this helps

**Comment by fetrarij** [comment]
This is actually the solution for this. Thanks @daanvanrobays
