### ISSUE TITLE
Locale.format does not change date formats

### ISSUE THREAD

**Issue by benplummer** [fetrarij/ngx-daterangepicker-material#67]
https://github.com/fetrarij/ngx-daterangepicker-material/blob/0b4ed0364973f4f201b5f69f1f730bbcb78099de/src/daterangepicker/daterangepicker.component.ts#L145-L149

Looking at the code above, it appears that even if a `format` is passed as part of the `locale`, it is not used.

I'm wondering if something like this would be more preferable:

```
if (!this.locale.format) { 
    if (this.timePicker) { 
        this.locale.format = moment.localeData().longDateFormat('lll'); 
    } else { 
        this.locale.format = moment.localeData().longDateFormat('L'); 
    } 
 }
```

This sets the format when one is not passed based on whether the timepicker is enabled or not. If a format is passed, we do not need to do anything.

What do you think?

I'm aware that the format could be set by overriding the moment formats for the relevant locale but I'm not sure that's very easy to do globally.

**Comment by fetrarij** [comment]
Hello, Thank you for the report. You are right, I will fix this.

**Comment by benplummer** [comment]
No worries, thanks!

**Comment by Ratikant01** [comment]
Thanks for raising this; when I set to:
[locale]="{applyLabel: 'Apply', format: 'YYYY-MM-DD', separator: '  to  '}"
it is not setting to desired format - always formatted as MM/DD/YYYY.
