### ISSUE TITLE
how to setting the global configuration?

### ISSUE THREAD

**Issue by finley-fuelx** [fetrarij/ngx-daterangepicker-material#69]
for example, I want to change default setting options,  add default range for each date-picker.
I don't know if I have it right now,  maybe we can use provider injection.
just like the [angular material](https://material.angular.io/components/snack-bar/overview#setting-the-global-configuration-defaults)

**Comment by fetrarij** [comment]
Great idea.

**Comment by fetrarij** [comment]
You can now , with the v1.3.0, [set the global locale](https://github.com/fetrarij/ngx-daterangepicker-material#global-locale)
