### ISSUE TITLE
transform dd / mm / yyyy It does not work.

### ISSUE THREAD

**Issue by manolait** [fetrarij/ngx-daterangepicker-material#73]
Hello,

I am applying this in my html

```
<div class="row">
    <div class="col s6">
        <input type="text" ngxDaterangepickerMd [(ngModel)]="selected" [locale]="locale" [showCustomRangeLabel]="true" [alwaysShowCalendars]="alwaysShowCalendars" [ranges]="ranges" [showClearButton]="true" [linkedCalendars]="true" [keepCalendarOpeningWithRange]="keepCalendarOpeningWithRange"
            [showRangeLabelOnInput]="showRangeLabelOnInput" class="form-control" placeholder="Rango de fechas..." />
    </div>
</div>
```

and in my ts:

locale: any = {
    customRangeLabel: 'Personalizar2',
    format: moment().format('dd/mm/yyyy'),
    separator: ' - ', // default is ' - '
    cancelLabel: 'Calcel', // detault is 'Cancel'
    applyLabel: 'Apply', // detault is 'Apply',
    daysOfWeek: [
      'Do',
      'Lu',
      'Ma',
      'Mi',
      'Ju',
      'Vi',
      'Sa'
  ],
  monthNames: [
      'Enero',
      'Febrero',
      'Marzo',
      'Abril',
      'Mayo',
      'Junio',
      'Julio',
      'Agusto',
      'Septiembre',
      'Octubre',
      'Noviembre',
      'Diciembre'
  ],
    firstDay: 1 // first day is monday
};

the name change in the months if it works, but in the date format no. It always shows MM / DD / YYYY and I need DD / MM / YYYY how do I solve it?

**Comment by fetrarij** [comment]
just use: 
```
{
...
format: 'DD/MM/YYYY'
...
}
```

**Comment by manolait** [comment]
Hello,

It does not work always appears MM / DD / YYYY.

Is this line of code necessary?

import {DaterangepickerDirective} from '../../../../src/daterangepicker/daterangepicker.directive';

**Comment by kishor-dabi** [comment]
Same issue ,
working on development but not work on production

**Comment by fetrarij** [comment]
Oh , I already fixed this issue but not yet released.
I will do a release as soon as possible and will let you know

**Comment by manolait** [comment]
I'm doing this installation:

npm install ngx-daterangepicker-material --save.



How can I download version v1.2.5?

A greeting.

**Comment by fetrarij** [comment]
You can install the 1.2.5 version with npm install `ngx-daterangepicker-material @1.2.5 --save.`
But wait for a few minutes, I'm releasing now

**Comment by manolait** [comment]
so waiting.

Thank you very much for the speed, it is amazing.

**Comment by fetrarij** [comment]
V1.2.7 is up. Thank you for reporting.
