### ISSUE TITLE
Inline and locale issue

### ISSUE THREAD

**Issue by daanvanrobays** [fetrarij/ngx-daterangepicker-material#75]
Hi,

When using the DaterangepickerComponent inline and setting the following locale
```
<ngx-daterangepicker-material [locale]="{format: 'DD/MM/YYYY HH:mm:ss', firstDay: 1}" >
</ngx-daterangepicker-material>
```
It throws this error

![image](https://user-images.githubusercontent.com/10880307/50291504-13b4ae80-046f-11e9-96da-9df8287690ef.png)

It looks like it has overwritten the locale entirely as it is not able to push the daysOfWeek array further since it is 'undefined'

**Comment by fetrarij** [comment]
Hello, thank you for the report. Will fix this.
