### ISSUE TITLE
Different models

### ISSUE THREAD

**Issue by R4upp** [fetrarij/ngx-daterangepicker-material#77]
Model properties are different!

In Custom ranges model is: `startDate` and `endDate`.
In Full Options model is: `start `and  `end`.

I start my `ngModel` with ` { startDate: moment(), endDate: moment() };`
But after change value, `ngModel `value is `{start: Moment, end: Moment}`.

**Comment by fetrarij** [comment]
Hello @R4upp ,  from full options we setted the [startKey and endKey](https://github.com/fetrarij/ngx-daterangepicker-material#startkey-and-endkey) .
Where is the wrong behaviour?

**Comment by R4upp** [comment]
Hello,
`ngModel `is initialized as `startDate `and `endDate`, but when the date is changed, the interface is changed to `start `and `end`.

I believe that after the date is changed, only the `ngModel `values should be changed and not their properties.

in [startkey-and-endkey](https://github.com/fetrarij/ngx-daterangepicker-material#startkey-and-endkey):
> the model we got would be: {start: Date, end: Date}

the correct would be: {startDate : Date, endDate: Date}

**Comment by fetrarij** [comment]
@R4upp But in full options we setted 
`  startKey="start"
  endKey="end"
`
That's why we have {start: Date, end: Date}

if you think  there are issue dont hesitate to reopen :)
