### ISSUE TITLE
No provider for LocalConfig

### ISSUE THREAD

**Issue by kenken023** [fetrarij/ngx-daterangepicker-material#81]
Good day!

I have recently updated the package from 1.2.6 to 1.3.0 but there is an error now.

Error: StaticInjectorError(AppModule)[DaterangepickerDirective -> LocaleConfig]: 
  StaticInjectorError(Platform: core)[DaterangepickerDirective -> LocaleConfig]: 
    NullInjectorError: No provider for LocaleConfig!

![image](https://user-images.githubusercontent.com/3609248/51095075-0f20b300-17ed-11e9-8d8b-353199a72f3b.png)

Can you please guide me on how to fix this? Thanks!
For workaround, I moved back to 1.2.6.

**Comment by fetrarij** [comment]
use `NgxDaterangepickerMd.forRoot()` instead of `NgxDaterangepickerMd` in imports.
