### ISSUE TITLE
how to set a default range?

### ISSUE THREAD

**Issue by rachel9955** [fetrarij/ngx-daterangepicker-material#82]
Say I have this list of ranges: 

ranges: any = {
    'Today': [moment(), moment()],
    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
    'Last Week': [moment().subtract(6, 'days'), moment()]
  }

By default, the selected range is "Today", and I want to change it so the selected range will be "Last Week".

How can I do that?
thanks!

**Comment by daanvanrobays** [comment]
Hi @rachel9955 

Try setting the start and end date of your datepicker to the 'Last Week' values.

```
@ViewChild(DaterangepickerComponent) datePicker: DaterangepickerComponent;

this.datePicker.setStartDate(moment().subtract(6, 'days'));
this.datePicker.setEndDate(moment());

this.datePicker.updateView();
```

**Comment by fetrarij** [comment]
You could just set the model with: `{start: moment().subtract(6, 'days'), end: moment()}`

eg : if you have `[(ngModel)]="myDate" `, you could do:
myDate = `{start: moment().subtract(6, 'days'), end: moment()}`

**Comment by rachel9955** [comment]
> You could just set the model with: `{start: moment().subtract(6, 'days'), end: moment()}`
> 
> eg : if you have `[(ngModel)]="myDate" `, you could do:
> myDate = `{start: moment().subtract(6, 'days'), end: moment()}`

Thanks, this works, but I want the **range** itself to be picked, so that in the input placeholder will be written "Last Week". (now it shows the date: 01-17-2019 - 01-11-2019)
I set "showRangeLabelOnInput" to true, but since the initial date is set manually and the range "Last Week" is not really picked on start, it's name is not shown on the input placeholder.

thanks.

**Comment by rachel9955** [comment]
I missed the brackets, it works now, thank you!!

**Comment by SShalini** [comment]
how to customize label for date range picker.

**Comment by fetrarij** [comment]
@SShalini hi, which label?

**Comment by SShalini** [comment]
Please refer screenshot where i explained clearly.

thanks,
Shalini

**Comment by paras-autviz** [comment]
thank you
