### ISSUE TITLE
Set current month to the right calendar and previous on the left one 

### ISSUE THREAD

**Issue by michaelbenavi** [fetrarij/ngx-daterangepicker-material#84]
Hi,

i'm using the inline component and i have some issues i need to solve:
 1. i need the right calendar to be the current month and the left to be the previous one.
 2. i open the component inside an angular materials mat-menu(open when clicking on 
     matMenuTriggerFor) - i need button Cancel to close the mat-menu, and from some reason the events 
     of rangeClicked, choosedDate, datesUpdated - are not triggered when selecting range ( when picking 
     dates ) 

Thanks,
Michael.

**Comment by AlaaHamoudah** [comment]
Yes, I do need the rtl support for the calendar as well, I need the from calendar to be on the right and the to the calendar to be on the left. 
How can we do this?

**Comment by fetrarij** [comment]
@AlaaHamoudah @michaelbenavi use "rtl" in `direction` attributes in [locale config](https://github.com/fetrarij/ngx-daterangepicker-material#locale). You can set a [global locale config ](https://github.com/fetrarij/ngx-daterangepicker-material#global-locale)too.

**Comment by Shyamjith05** [comment]
I want to show previous month first and current month second .

**Comment by iamandreadompe** [comment]
Hi @Shyamjith05 i've the same needs,
try with this https://github.com/fetrarij/ngx-daterangepicker-material/issues/154
