### ISSUE TITLE
Not able to import LocaleConfig directly

### ISSUE THREAD

**Issue by veerritu** [fetrarij/ngx-daterangepicker-material#89]
Hi,

I am using this library to create a wrapper library for my project.
Bur when I am trying to import **LocaleConfig** , I am not able to import it directly.
Please let me know what can be wrong.

![image](https://user-images.githubusercontent.com/32728268/51887377-880d3680-23b9-11e9-99cb-8682198eca3f.png)

if I add import with **import { LocaleConfig } from 'ngx-daterangepicker-material/daterangepicker.config';**
then I am getting below error:
![image](https://user-images.githubusercontent.com/32728268/51889789-754a3000-23c0-11e9-904f-74998c1d12bf.png)

why is daterangepicker.config' not exported in index.d.ts in library.

**Comment by LeParadoxHD** [comment]
Same here...

**Comment by veerritu** [comment]
Pull request https://github.com/fetrarij/ngx-daterangepicker-material/pull/91  for this has been merged 👍 


Now LocaleConfig can be imported directly.

Thank you @fetrarij .

**Comment by fetrarij** [comment]
Thanks @veerritu

**Comment by veerritu** [comment]
@fetrarij  something is still missing , now that you have added injection token and LOCALE_CONFIG.
May be this new LOCALE_CONFIG should be added to the exports as well.

**Comment by veerritu** [comment]
I will raise a PR to add LOCALE_CONFIG to exports.
![image](https://user-images.githubusercontent.com/32728268/51976210-1f51b700-24aa-11e9-80c0-c00d093203e7.png)

**Comment by fetrarij** [comment]
@veerritu Already in 1.3.2, there are a bug in 1.3.1 I needed to add some fixes, then just saw your message and added theses in index.ts

**Comment by veerritu** [comment]
@fetrarij  yes just checked new version.
But damn its a chain reaction :) 
now LocaleService is missing.

![image](https://user-images.githubusercontent.com/32728268/51979357-f7b31c80-24b2-11e9-9214-9fd8d6ce2025.png)

**Comment by fetrarij** [comment]
@veerritu v1.3.3 is up. Feel free to open PR if you found some bug :)

**Comment by veerritu** [comment]
@fetrarij  thanks a ton for quick response, its finally working. I would be working on this now and would surely contribute for PRs if required. 👍
