### ISSUE TITLE
Select week start date

### ISSUE THREAD

**Issue by zolakt** [fetrarij/ngx-daterangepicker-material#9]
I don't see an option for changing the start date of the week, ex. set it to Monday.
It would be very useful

**Comment by fetrarij** [comment]
Hello,
Thanks for theses issues. I'll work on these next week.
This one is not clear for me, you mean to add a button to select the monday of current week?

**Comment by zolakt** [comment]
Hi, thanks for the reply.

No, not a button in the UI, just a input config option, where you can set the first day of the week that will be rendered. Basically, I want the calendar to render from Monday, not Sunday... most of people outside US do. 

Most date picker libs have a similar options, for example the bootstrap plugin you refer to has a "firstDay" property inside the "locale" object. https://github.com/dangrossman/daterangepicker/issues/289

**Comment by fetrarij** [comment]
Okay, got it now.
Thank you very much for your interest and time for creating issue.
Will work on this ;)

**Comment by fetrarij** [comment]
You can set this with locale.firstDay.

Thank you.

**Comment by Franccescalee** [comment]
I just checked the local in my browser and it is en-US but the datepicker is showing Wednesday as the first day of the week.

**Comment by oleksandr-kupenko** [comment]
It's Wednesday too. I have no idea who has Wednesday as the first day of the week.

**Comment by oleksandr-kupenko** [comment]
> 

[locale]="{format: 'DD/MM/YYYY HH:mm:ss', firstDay: 1}
