### ISSUE TITLE
Not working in bundled file in Angular 7

### ISSUE THREAD

**Issue by ranjeettamil** [fetrarij/ngx-daterangepicker-material#98]
In development environment is working fine, It is not working in bundled file ("npm run build").
Currently i am using angular 7,
ngx-daterangepicker-material - 1.3.0,

I am getting error in production now, My development is done but now facing problem in prodcution.

Getting error like below and application is crashed,

![image](https://user-images.githubusercontent.com/46807293/52114759-e8f37380-2632-11e9-8f5b-0bb422d0295f.png)

**Console Error :**
Cannot read property 'NaN' of undefined

Please help to resolve this issue. Thanks in advance.

**Comment by fetrarij** [comment]
It seems already fixed. Which version are you using? Could you try to add some default locale config in forRoot() ?

**Comment by ranjeettamil** [comment]
Hi Fetrarij,

I tried with some default locale config in forRoot,

NgxDaterangepickerMd.forRoot({
      format: 'MM/DD/YYYY',
      separator: ' To ', // default is ' - '
      cancelLabel: 'Cancel', // detault is 'Cancel'
      applyLabel: 'Okay', // detault is 'Apply'
  }),
and updated the to latest version - 2.0.1.

It working fine, Thanks a lot for saving my time.

**Comment by fetrarij** [comment]
Hi @ranjeettamil if using the version 2.0.1 you even dont need to add default locale config
