### ISSUE TITLE
same month are visible at same time

### ISSUE THREAD

**Issue by veerritu** [fetrarij/ngx-daterangepicker-material#99]
Please see below: how this can be avoided:

![image](https://user-images.githubusercontent.com/32728268/52121194-c1a5a200-2644-11e9-9189-8172c50d5a48.png)

**Comment by fetrarij** [comment]
Hello @veerritu , could you explain how to reproduce thid behaviour?  Which version are you using? Thanks

**Comment by veerritu** [comment]
Hi @fetrarij 
If you see at demo : https://fetrarij.github.io/ngx-daterangepicker-material/simple
Actually I think the there should be only two checvron buttons at start and end so that we can change both months at a time , but if you give 4 chevron buttons two both of them then this issue will come, like there can be same months at both end.

To reproduce: just select march at left and on the right similarly , and you would be able to see this problem.

![image](https://user-images.githubusercontent.com/32728268/52161608-801d0180-26ed-11e9-8f26-3dec30d23216.png)

See below example : 
There are only two arrow buttons to change months:

![image](https://user-images.githubusercontent.com/32728268/52161643-531d1e80-26ee-11e9-9461-228fc1cb3cfd.png)

**Comment by veerritu** [comment]
Hi @fetrarij 
is there anything to set locale to particular country's language?

I can see you are all caught up .... but no worries please do reply once you get some time.
TIA :) 👍

**Comment by fetrarij** [comment]
@veerritu hi, just use moment.locale(YOUR_LANG); in your component, then pass value in locale data

eg in your component:

```typescript
moment.locale('fr');
@Component({
  selector: 'simple',
  templateUrl: './simple.component.html',
  styleUrls: ['./simple.component.scss']
})
export class SimpleComponent implements OnInit {
  locale = {
   daysOfWeek: moment.weekdaysMin(),
   monthNames: moment.monthsShort(),
   firstDay: moment.localeData().firstDayOfWeek()
  };
  ...
}
```

and html:

```html
<input type="text" ngxDaterangepickerMd
    [(ngModel)]="selected" class="form-control" placeholder="Choose date"
    [locale]="locale">
```

**Comment by veerritu** [comment]
@fetrarij  worked thanks.
and any update on same month visible issue ?  were you able to reproduce?
https://github.com/fetrarij/ngx-daterangepicker-material/issues/99#issuecomment-459945106

**Comment by fetrarij** [comment]
@veerritu both calendar are there , not linked, if you want them to be linked, add [linkedCalendars]="true"

**Comment by veerritu** [comment]
@fetrarij  thank you .. closing this.

**Comment by veerritu** [comment]
@fetrarij  Is there any way to open this picker from an icon and also can this picker be toggled from any attribute?

**Comment by fetrarij** [comment]
@veerritu yes, look at the demo https://fetrarij.github.io/ngx-daterangepicker-material/simple there are a button "open from a button"

code are:
- https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.html
- https://github.com/fetrarij/ngx-daterangepicker-material/blob/master/demo/src/app/simple/simple.component.ts

dont forget to have class="ngx-daterangepicker-action" on the button

**Comment by veerritu** [comment]
@fetrarij  the 'applyLabel'  button text doesn't get translated when locale is set.
Can this be fixed?

**Comment by veerritu** [comment]
> How do you define the locale @veerritu ? this should be

@fetrarij  I am following this exactly : https://github.com/fetrarij/ngx-daterangepicker-material/issues/99#issuecomment-460142477

**locale = {
    daysOfWeek: moment.weekdaysMin(),
    monthNames: moment.monthsShort(),
    firstDay: moment.localeData().firstDayOfWeek(),
    format: 'DD.MM.YYYY',
    applyLabel: 'apply'
  };**
what do we add to translate that applyLabel, i couldnt find anything in moment.

**Comment by fetrarij** [comment]
Hello, in applyLabel just put the text you want to display @veerritu

**Comment by veerritu** [comment]
> Hello, in applyLabel just put the text you want to display @veerritu

But that will be hardcoded right , because i want it to be changed as per the language set in moment.locale('fr');

**Comment by fetrarij** [comment]
@veerritu  no it's not hardcoded. 
with moment.locale('fr') it would just translate all month and day name, all label in the daterangepicker should be specified with locale config (applyLabel & cancelLabel), they are string, if you use a translator plugin you just need to set applyLabel: SOMESTRING_TRANSLATED

**Comment by veerritu** [comment]
@fetrarij  ok so for labels I will have to use another plugin.

**Comment by veerritu** [comment]
i will give it a try... and also i was checking on isShown flag to toggle this picker when clicked on input field but somehow the flag remains false even if the picker gets opened.
